</div><div class="container">

<div class="greyarea sec1">
    <img src="../skin/frontend/numanna/default/images/misc/seal-25plus.png">
    <p>NuManna is proud to introduce the first ever line of Organic Long-Term Food Storage Products. These products are all organically certified, scientifically backed and hands down the best food storage products on the market today.  These healthy meals are ready to fix in an instant, they taste great and they can also be used multiple times due to their convenient re-sealable bags. </p>
    <p>What you put into your body during times of duress truly matters and NuManna’s organic meals are clean, healthy and packed with nutrition for your family’s most important moments. </p>
</div>
<div class="whitearea sec2">
<img src="../media/Food-Bucket-Chart-organized.jpg">
</div>
<div class="orangearea sec3">
    <div class="subsec3"><h3>Easy to make</h3>Create a terrific organic meal for you and your family by just  simply boiling water and following the easy to use directions on the bag.</div>

    <div class="subsec3"><h3>Great NuManna taste</h3>The NuManna line of organic food storage 	products has the same great taste that you are used to. </div>

    <div class="subsec3"><h3>Perfect for every day use</h3>This food is clean, healthy and packed with nutrition.  Your family will want to eat it everyday.</div>

    <div class="subsec3"><h3>Quality you Expect</h3>
        <ul>
            <li>25 Year Shelf Life</li>
            <li>NO Preservatives</li>
        	<li>GMO FREE</li>
            <li>Pesticide Tested</li>
        	<li>MSG FREE </li>
            <li>Heavy Metals Tested</li>
        	<li>Made in America</li>
        </ul>
    </div>
</div>



    <div class="row">
        <div class="span3 center"><img src="<?php echo $this->getSkinUrl(); ?>images/misc/pp1.jpg" class="mb" style="float:right; margin-bottom:40px; margin-right:20px;" alt="">
            <a href="http://numanna.transformagency.com/products/organic/universal-faucet-adapter.html" class="btn btn-primary">Order Now</a>
        </div>
        <div class="span9">
            <h2>Organic Family Pack</h2>
            <p>
            	Includes 162 Total Servings of organic goodness.
                <ul>
            	<li>Organic Powdered Milk - 40 Servings</li>
            	<li>Organic Cheddar Broccoli Soup - 10 Servings</li>
            	<li>Organic Classic Chili  - 10 Servings</li>
            	<li>Organic Oatmeal and Brown Sugar - 20 Servings</li>
            	<li>Organic Pasta Primavera - 10 Servings</li>
            	<li>Organic Italian Pasta with Marinara - 10 Servings</li>
            	<li>Organic Chia Seeds - 16 Servings</li>
            	<li>Organic Sweet Habanero Chili with Pineapple - 10 Servings </li>
            	<li>Organic Mac n Cheese - 10 Servings</li>
            	<li>Organic Pancake Mix - 10 Servings</li>
            	<li>Organic Quinoa - 16 Servings</li>
                </ul>
            </p>
        </div>
    </div>

    <hr/>

    <div class="row">
        <div class="span3 center"><img src="<?php echo $this->getSkinUrl(); ?>images/misc/pp2.jpg" class="mb" style="float:right; margin-bottom:40px; margin-right:20px;"  alt="">
            <a href="http://numanna.transformagency.com/products/organic/universal-faucet-adapter.html" class="btn btn-primary">Order Now</a>
        </div>
        <div class="span9">
                <h2>Organic Freeze Dried Meats</h2>
                <p>NuManna Freeze Dried Meats are 100% North American USDA certified and a convenient and delicious solution for building a food storage supply. Prepare for the survival of you and your family in nearly any situation with 100% USDA Freeze Dried Meats that sustain nutrition for up to 25 years.  NuManna survival foods are stored in highly durable and re-sealable Mylar pouches that are sealed with an oxygen absorber to preserve the longevity of your food storage supply.  Because our packaging is ultra-light weight and compact, it will make transporting, storing, and preparing your food during an emergency that much easier.</p>
                <p>Our 100% North American USDA Freeze Dried Meats will make any long-term storage supply more complete. You and your family will be able to enjoy as a main dish or as a delicious, nutrient-dense addition to chili, soups, stews or other food storage meals like pasta. Prevent a case of iron-deficiency that can occur even when food selection is not limited by making freeze-dried meats available in your survival supply. Every serving of freeze-dried meat provides you with the iron, calories, vitamins and protein you need for long-term survival.</p>

                <p>Our survival food ingredients offer more calories per pound than top competing food storage companies. Liven up your long-term food supply with 100% North American USDA freeze dried meats and increase your chances, and quality, of survival in an emergency situation. Gain the peace of mind you want from knowing you and your family are prepared. </p>

                <ul>
                <li>Freeze-Dried, High Quality Ingredients</li>
                <li>100% North American USDA Certified</li>
                <li>Resealable Bags</li>
                <li>Lasts up to 1 month after opening in dry form (Up to 3 months if refrigerated)</li>
                <li>Simple to Prepare – Just Add Water to Rehydrate</li>
                <li>Ready to eat in 15 minutes</li>
                <li>Up to 25 year shelf life</li>
                <li>Great addition to your Food Storage or perfect for Daily Use </li>
                </ul>
                <br/>

                <h2>Packaging:</h2>

                <ul>
                <li>Mylar Pouches</li>
                <li>Extra Heavy-duty (5.4 Mils) Ziplocked and Heat Sealed </li>
                <li>Complete aluminum foil layer core (.00035)</li>
                <li>Oxygen Absorber in each pouch</li>
                </ul>
                <br/>

                <h2>Cooking Instructions</h2>

                <p>Remove Oxygen absorber and place 2 cups of Boiling Water into Pouch and Reseal. Let stand for 10-12 minutes.  Open package and stir.  Product temperature must reach 160 degrees.   Caution: Product will be HOT.</p>
        </div>
    </div>

    <hr/>

    <div class="row">
        <div class="span3 center"><img src="<?php echo $this->getSkinUrl(); ?>images/misc/pp3.jpg" class="mb" style="float:right; margin-bottom:40px; margin-right:20px;"  alt="">
            <a href="http://numanna.transformagency.com/products/organic/universal-faucet-adapter.html" class="btn btn-primary">Order Now</a>
        </div>
        <div class="span9">
            <h2>Premium Organic Milk Powder</h2>
            <p>NuManna has made it very easy to store and use a high quality milk product as part of your long term food storage. Each bag has a resealable top for convenience and to prevent spoilage.  Preparation is simple.  Pour the milk powder into a cup of water, stir vigorously and the milk will mix easily and tastes surprisingly like store bought milk.  In fact, it may be even better, because NuManna milk packs are all HORMONE-FREE and of the highest USDA standards. And now, for the first time, you can buy Organic Milk Powder from a long-term storage company.</p>
                <p>In our pursuit of superior products, NuManna has always been ahead of the curve in our industry. Our new Organic Milk Powder is just another example of what we are all about. We focus on manufacturing the best products for our family so you will never regret having NuManna to serve to yours. NuManna is now the first food storage company to offer organic milk powder. Also, all our milk receives our proprietary bio-enhancement treatment and packaged correctly for long term storage before it is labeled NuManna.</p>
        </div>
    </div>




</div>
