<div class="container">

    <h2>The Importance of Organic Food</h2>
    <p class="big">NuManna is proud to introduce the first ever line of organic long-term food-preparedness products. NuManna offers a complete line of ready-to-use, USDA certified organic meals that store for up to 30 years. These are real, nutritious, wholesome meals -- not sugar and oatmeal, toxic additives, or unhealthy fillers. </p>
    <br/>
    <div class="row">
        <div class="span6">
            <h4>The NuManna Advantage</h4>
            <p>Gain the peace of mind knowing that you and your family are prepared for whatever surprises life may throw at you.</p>
            <ul>
            <li>100% USDA certified organic</li>
            <li>No toxins, harmful additives, or sugary fillers</li>
            <li>Re-sealable bags means no waste</li>
            <li>Lasts up to 1 month after opening (or up to 3 months refrigerated)</li>
            <li>15 minute prep time: just add water to rehydrate, heat, and serve.</li>
            <li>Up to 25-year shelf life. Simply the highest-quality product of its kind.</li>
            </ul>

            <h4>Organic That's Super Easy to Prepare</h4>
            <p>These healthy and wholesome organic meals are ready to serve in an instant, they taste great, and they can also be reused due to their convenient re-sealable bags. Create a terrific, delicious, organic meal for you and your family by simply boiling water and following the easy-to-use directions on the bag. It's that easy.</p>
        </div>
        <div class="span6">
            <h4>Stay Well During a Crisis</h4>
            <p>During times of stress or crisis, your body requires extra nutrition to maintain a strong immune system to protect your physical and mental wellness. NuManna's organic meals are wholesome, healthy and packed with bio-available nutrition for critical moment when your family's systems may be taxed by unexpected or intense stress.</p>
            <h4>More Calories Equals Better Value</h4>
            <p>When a crisis strikes, it's not the time to go on the latest Hollywood diet: calories will become your best friend. Calories are what will keep you alive when supermarket shelves are empty. Our survival foods offer more calories per pound than top competing food-storage companies. We live in uncertain times. NuManna's long-term food storage solutions can help ensure your family's long-term well being, under any circumstances to come.</p>
        </div>
    </div>

    <div class="row">
        <div class="span4">
            <img src="<?php echo $this->getSkinUrl(); ?>images/misc/pp1.jpg" class="mb" alt="">
            <h2>Family Pack</h2>
            <p>In lacinia ligula mi, et congue libero ultricies nec. Donec vel lacus nibh. Aenean posuere gravida ligula, nec vestibulum arcu lobortis id. Sed lacus felis, condimentum et lorem in, porta dictum neque.</p>
            <a href="#" class="btn btn-primary">Order Now</a>
        </div>
        <div class="span4">
            <img src="<?php echo $this->getSkinUrl(); ?>images/misc/pp2.jpg" class="mb"  alt="">
            <h2>Meat </h2>
            <p>In lacinia ligula mi, et congue libero ultricies nec. Donec vel lacus nibh. Aenean posuere gravida ligula, nec vestibulum arcu lobortis id. Sed lacus felis, condimentum et lorem in, porta dictum neque.</p>
            <a href="#" class="btn btn-primary">Order Now</a>
        </div>
        <div class="span4">
            <img src="<?php echo $this->getSkinUrl(); ?>images/misc/pp3.jpg" class="mb"  alt="">
            <h2>Milk</h2>
            <p>In lacinia ligula mi, et congue libero ultricies nec. Donec vel lacus nibh. Aenean posuere gravida ligula, nec vestibulum arcu lobortis id. Sed lacus felis, condimentum et lorem in, porta dictum neque.</p>
            <a href="#" class="btn btn-primary">Order Now</a>
        </div>
    </div>


</div>