</div><div class="container">

<div class="greyarea sec1">
    <img src="../skin/frontend/numanna/default/images/misc/seal-25plus.png">
    <p>NuManna is proud to introduce the first ever line of Organic Long-Term Food Storage Products. These products are all organically certified, scientifically backed and hands down the best food storage products on the market today.  These healthy meals are ready to fix in an instant, they taste great and they can also be used multiple times due to their convenient re-sealable bags. </p>
    <p>What you put into your body during times of duress truly matters and NuManna’s organic meals are clean, healthy and packed with nutrition for your family’s most important moments. </p>
    <div class="clear"></div>
</div>


<div class="orangearea sec2">
    <div class="subsec1">
        <h3>Easy to make</h3>Create a terrific organic meal for you and your family by just  simply boiling water and following the easy to use directions on the bag.

        <h3>Great NuManna taste</h3>The NuManna line of organic food storage 	products has the same great taste that you are used to.

        <h3>Perfect for every day use</h3>This food is clean, healthy and packed with nutrition.  Your family will want to eat it everyday.
    </div>

    <div class="subsec2"><h3>Quality you Expect</h3>
        <ul>
            <li>25 Year Shelf Life</li>
            <li>NO Preservatives</li>
        	<li>GMO FREE</li>
            <li>Pesticide Tested</li>
        	<li>MSG FREE </li>
            <li>Heavy Metals Tested</li>
        	<li>Made in America</li>
        </ul>
    </div>
    <div class="subsec3">
        <img src="../media/Food-Bucket-Chart-organized.jpg">
    </div>
    <div class="clear"></div>
</div>



    <div class="row">
        <div class="span4 center"><img src="<?php echo $this->getSkinUrl(); ?>images/misc/pp1.jpg" class="mb" style="float:right; margin-bottom:40px; margin-right:20px;" alt="">
            <a href="../products/organic-family-pack.html" class="btn btn-primary">Order Now</a>
             <h2>Organic Family Pack</h2>
            <p>
                Includes 162 Total Servings of organic goodness.
                <ul>
                <li>Organic Powdered Milk - 40 Servings</li>
                <li>Organic Cheddar Broccoli Soup - 10 Servings</li>
                <li>Organic Classic Chili  - 10 Servings</li>
                <li>Organic Oatmeal and Brown Sugar - 20 Servings</li>
                <li>Organic Pasta Primavera - 10 Servings</li>
                <li>Organic Italian Pasta with Marinara - 10 Servings</li>
                <li>Organic Chia Seeds - 16 Servings</li>
                <li>Organic Sweet Habanero Chili with Pineapple - 10 Servings </li>
                <li>Organic Mac n Cheese - 10 Servings</li>
                <li>Organic Pancake Mix - 10 Servings</li>
                <li>Organic Quinoa - 16 Servings</li>
                </ul>
            </p>
        </div>

        <div class="span4 center"><img src="<?php echo $this->getSkinUrl(); ?>images/misc/pp2.jpg" class="mb" style="float:right; margin-bottom:40px; margin-right:20px;"  alt="">
            <a href="../products/organic-family-pack.html" class="btn btn-primary">Order Now</a>
            <h2>Organic Freeze Dried Meats</h2>
            <p>
                NuManna Freeze Dried Meats are 100% North American USDA certified and a convenient and delicious solution for building a food storage supply.

                <ul>
                <li>Freeze-Dried, High Quality Ingredients</li>
                <li>100% North American USDA Certified</li>
                <li>Resealable Bags</li>
                <li>Lasts up to 1 month after opening in dry form (Up to 3 months if refrigerated)</li>
                <li>Simple to Prepare – Just Add Water to Rehydrate</li>
                <li>Ready to eat in 15 minutes</li>
                <li>Up to 25 year shelf life</li>
                <li>Great addition to your Food Storage or perfect for Daily Use </li>
                </ul>
            </p>
        </div>

        <div class="span4 center"><img src="<?php echo $this->getSkinUrl(); ?>images/misc/pp3.jpg" class="mb" style="float:right; margin-bottom:40px; margin-right:20px;"  alt="">
            <a href="../products/3-pack-of-premium-organic-milk-powder-40-serving-pouch.html" class="btn btn-primary">Order Now</a>
             <h2>Organic Family Pack</h2>
               <p>In our pursuit of superior products, NuManna has always been ahead of the curve in our industry. Our new Organic Milk Powder is just another example of what we are all about. We focus on manufacturing the best products for our family so you will never regret having NuManna to serve to yours. NuManna is now the first food storage company to offer organic milk powder. Also, all our milk receives our proprietary bio-enhancement treatment and packaged correctly for long term storage before it is labeled NuManna.</p>
        </div>



    </div>


    <hr/>

   <!--  <div class="row">
        <div class="span3 center"><img src="<?php echo $this->getSkinUrl(); ?>images/misc/pp3.jpg" class="mb" style="float:right; margin-bottom:40px; margin-right:20px;"  alt="">
            <a href="http://numanna.transformagency.com/products/organic/universal-faucet-adapter.html" class="btn btn-primary">Order Now</a>
        </div>
        <div class="span9">
            <h2>Premium Organic Milk Powder</h2>
            <p>NuManna has made it very easy to store and use a high quality milk product as part of your long term food storage. Each bag has a resealable top for convenience and to prevent spoilage.  Preparation is simple.  Pour the milk powder into a cup of water, stir vigorously and the milk will mix easily and tastes surprisingly like store bought milk.  In fact, it may be even better, because NuManna milk packs are all HORMONE-FREE and of the highest USDA standards. And now, for the first time, you can buy Organic Milk Powder from a long-term storage company.</p>

        </div>
  --> </div>




</div>
