<div class="testimonials" style="padding-top:0; ">
      <div class="video"><iframe width="100%" height="415" frameborder="0" allowfullscreen="" wmode="Opaque" src="//www.youtube.com/embed/h4gN2dtkO0I"/></iframe></div>

      <hr/>

      <p class="testimonial">"I have tried several different brands of storable foods and NuManna has been the best. The food looks like actual food. Although it was difficult to pick a favorite as all are delicious...makes my mouth salivate just typing about it! Thank you NuManna for making incredible food!"</p>
      <p class="author">
      <strong>— Jayme, Texas</strong>
      </p>

      <hr/>

      <p class="testimonial">"I really appreciate the high quality non GMO products you carry and I especially like the packaging. Very professional to say the least. I really like spicy chili and your habanero chili is the best, in my opinion. Thanks for the custom order. <br/>You make it so that having an emergency supply doesn't have to feel like I'm "roughing it" so thanks for that! I've had to reorder since I sometimes enjoy Numanna even in the good times..."</p>
      <p class="author">
      <strong>— James, San Antonio, Lone Star State</strong>
      </p>

      <hr/>

      <p class="testimonial">"I have tried all kinds of food storage...this is the best tasting food of any I've tried."</p>
      <p class="author">
      <strong>— Gayle, Springville, UT</strong>
      </p>

      <hr/>

      <p class="testimonial">"I was very surprised after eating NuManna. First it tastes great. Second, most storable foods give me a bit of an uneasy feeling after eating them. I have food sensitivities. I did not experience any of the typical stomach problems for eating a dehydrated food product. NuManna is the best I have ever had."</p>
      <p class="author">
      <strong>— Tim C., California</strong>
      </p>

      <hr/>

      <p class="testimonial">"This stuff is awesome. My wife has been away for a while so I ate NuManna while she was gone. It was simple and everything I had was really good. I wish NuManna was around when I bought a bunch of bulk food in the past from the Mormons. I don’t want to have all these ingredients and put them together. NuManna was simple and great tasting. I gave away all my other bulk food."</p>
      <p class="author">
      <strong>— Reagan B., Mexico</strong>
      </p>

      <hr/>

      <p class="testimonial">"I host a national radio show and I have been around this industry for a long time and seen just about everything that is out there. I have never tasted storable food as good as NuManna and I’ll put my name on that. My wife and I took some of the Pasta Primavera to a church function and people couldn’t believe this was storable food. It was so creamy. The Habanero chili could win a cook-off it’s that good. NuManna is the brand we recommend because it is the best we have ever tasted and the People behind the company are first rate."</p>
      <p class="author">
      <strong>— Pastor Butch, West Virginia</strong>
      </p>

      <p class="testimonial">"I’ve been in search of a storable food product that would help you and your family. I’ve tested a number of products and I’ve researched a number of companies and I actually have finally come up with a company and a product line that I believe that you need to utilize to help protect yourself and your family. The name of the company is NuManna."</p>
      <p class="author">
      <strong>— Dr. Dave Janda</strong>
      </p>

      <p class="testimonial">"I received the sampler pack last week and was pleasantly surprised at how good the food is. The portion size was perfect for both my husband and I to try. His comment was, ‘this is actually really good tasting’. Also, the fact that this is non-gmo food is a major plus! We will definitely be ordering from you again. Thank you so much for a great product, and offering the sample packs to try."</p>
      <p class="author">
      <strong>— Sherrie S.</strong>
      </p>

      <p class="testimonial">"I have done a lot of research over the past 5 to 6 months.  I keep coming back to your brand and business model time after time when comparing to other survival foods. I look forward to receiving your products soon. Cheers."</p>
      <p class="author">
      <strong>— David W.</strong>
      </p>

      <p class="testimonial">"I believe that this is one of the best investments that you can make for your family to be prepared for what ever the future might hold. Remember… you can’t eat gold, but you can eat NuManna Food Storage during a time of crisis."</p>
      <p class="author">
      <strong>— Joyce Riley host of The Power Hour</strong>
      </p>

      <p class="testimonial">"There are excesses of organizations stuffing their pails with sugary beverage blends and abandons. NuManna has genuine nourishment that manages you in a crisis circumstance... GMO Free, simple to alter dinners and natural superfoods. Simple to transport and 25 or more year time span of usability. Everybody needs to consider their independence. NuManna has turned into the foundation of my long haul sustenance stockpiling. NuManna is nourishment stockpiling you’ll adore to eat."</p>
      <p class="author">
      <strong>— Steve Quayle</strong>
      </p>

</div>