<div class="row videos">
   <div class="span6 video">
          <h5>Installing your Walla</h5>
          <iframe src="http://www.youtube.com/embed/_gnSNk7fkPU" frameborder="0" width="100%" height="300"/></iframe>
   </div>
   <div class="span6 video">
          <h5>Changing your Walla</h5>
          <iframe src="http://www.youtube.com/embed/oV25TmP1X5s" frameborder="0" width="100%" height="300"/></iframe>
   </div>
</div>
<div class="row videos">
   <div class="span6 video">
          <h5>Measuring your wall</h5>
          <iframe src="http://www.youtube.com/embed/uG2tBCgRz0A" frameborder="0" width="100%" height="300"/></iframe>
   </div>
   <div class="span6 video">
          <h5>Changing your Walla</h5>
          <iframe src="http://www.youtube.com/embed/oV25TmP1X5s" frameborder="0" width="100%" height="300"/></iframe>
   </div>
</div>