
<div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
<div class="page-title">
    <h1><?php echo Mage::helper('contacts')->__('Contact Us') ?></h1>
</div>
<form action="<?php echo $this->getFormAction(); ?>" id="contactForm" method="post">
    <div class="fieldset rel">
        <div class="contact-info">
            <address>
                    <h2><strong class="name"><?php echo Mage::getStoreConfig('general/store_information/name'); ?></strong></h2>
                    <p><?php echo Mage::getStoreConfig('general/store_information/address');    ?></p>
                    <p><strong>Phone: <?php echo Mage::getStoreConfig('general/store_information/phone'); ?></strong></p>
                    <!--<p><strong><?php echo Mage::getStoreConfig('trans_email/ident_general/name');?></strong> :<br /> <a href="mailto:<?php echo Mage::getStoreConfig('trans_email/ident_general/email'); ?>"><?php echo Mage::getStoreConfig('trans_email/ident_general/email'); ?></a></p>
                    <p><strong><?php echo Mage::getStoreConfig('trans_email/ident_sales/name');?></strong> :<br /> <a href="mailto:<?php echo Mage::getStoreConfig('trans_email/ident_sales/email'); ?>"><?php echo Mage::getStoreConfig('trans_email/ident_sales/email'); ?></a></p>-->
                    <p><strong><?php echo Mage::getStoreConfig('trans_email/ident_support/name');?></strong> :<br /> <a href="mailto:<?php echo Mage::getStoreConfig('trans_email/ident_support/email'); ?>"><?php echo Mage::getStoreConfig('trans_email/ident_support/email'); ?></a></p>
            </address>
        </div>
        <ul class="form-list">
            <!--<li class="wide">
                <p>Fusce congue enim ut leo tristique commodo a at tellus. Fusce congue enim ut leo tristique commodo a congue enim ut leo tristique commodo.</p>
            </li>-->
            <li class="fields">
                <div class="field">
                    <label for="name" class="required"><em>*</em><?php echo Mage::helper('contacts')->__('Name') ?></label>
                    <div class="input-box">
                        <input name="name" id="name" title="<?php echo Mage::helper('contacts')->__('Name') ?>" value="<?php echo $this->htmlEscape($this->helper('contacts')->getUserName()) ?>" class="input-text required-entry" type="text" />
                    </div>
                </div>
                <div class="field">
                    <label for="email" class="required"><em>*</em><?php echo Mage::helper('contacts')->__('Email') ?></label>
                    <div class="input-box">
                        <input name="email" id="email" title="<?php echo Mage::helper('contacts')->__('Email') ?>" value="<?php echo $this->htmlEscape($this->helper('contacts')->getUserEmail()) ?>" class="input-text required-entry validate-email" type="text" />
                    </div>
                </div>
            </li>
            <li>
                <label for="telephone"><?php echo Mage::helper('contacts')->__('Telephone') ?></label>
                <div class="input-box">
                    <input name="telephone" id="telephone" title="<?php echo Mage::helper('contacts')->__('Telephone') ?>" value="" class="input-text" type="text" />
                </div>
            </li>
            <li>
                <label for="subject"><?php echo Mage::helper('contacts')->__('Subject') ?></label>
                <div class="input-box">
              <!--       <select name="subject" id="subject" title="<?php echo Mage::helper('contacts')->__('Subject') ?>" class="input-text" >
                        <option>Option 1</option>
                        <option>Option 2</option>
                    </select> -->

                    <input name="subject" id="subject" title="<?php echo Mage::helper('contacts')->__('Subject') ?>" value="" class="input-text" type="text" />


                </div>
            </li>
            <li class="wide">
                <label for="comment" class="required"><em>*</em><?php echo Mage::helper('contacts')->__('Comment') ?></label>
                <div class="input-box">
                    <textarea name="comment" id="comment" title="<?php echo Mage::helper('contacts')->__('Comment') ?>" class="required-entry input-text" cols="5" rows="3"></textarea>
                </div>
            </li>
        </ul>
        <div class="clear"></div>
    </div>
    <div class="buttons-set">
        <input type="text" name="hideit" id="hideit" value="" style="display:none !important;" />
        <p class="required fl"><?php echo Mage::helper('contacts')->__('* Required Fields') ?></p>
        <button type="submit" title="<?php echo Mage::helper('contacts')->__('Submit') ?>" class="fr btn btn-primary"><span><span><?php echo Mage::helper('contacts')->__('Submit Message') ?></span></span></button>
    </div>
</form>
<script type="text/javascript">
//<![CDATA[
    var contactForm = new VarienForm('contactForm', true);
//]]>
</script>
