<?php if(count($this->getItemCollection()->getItems())): ?>
<div class="box-collateral box-up-sell">
    <h2><?php echo $this->__('You might also like') ?></h2>
    <ul class="products-grid grid-upsell" id="upsell-product-table">
    <?php // $this->setColumnCount(3);  ?>
    <?php $this->resetItemsIterator() ?>
    <?php for($_i=0;$_i<$this->getRowCount();$_i++): ?>

        <?php for($_j=0;$_j<$this->getColumnCount();$_j++): ?>
            <?php if($_link=$this->getIterableItem()): ?>
            <li class="item">
                <a href="<?php echo $_link->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_link->getName()) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_link, 'small_image')->resize(230,155) ?>" alt="<?php echo $this->htmlEscape($_link->getName()) ?>" /></a>
                <h3 class="product-name"><a href="<?php echo $_link->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_link->getName()) ?>"><?php echo $this->htmlEscape($_link->getName()) ?></a></h3>
                <?php  echo $this->getPriceHtml($_link, true, '-upsell') ?>

                <div class="actions">
                  <button type="button" title="<?php echo $this->__('Configure Now') ?>" class="btn btn-primary" onclick="setLocation('<?php echo $_link->getProductUrl() ?>')"><?php echo $this->__('Add to Cart') ?></button>
                         <a class="link-wishlist" href="#">Add to Wishlist</a>
                </div>
            </li>
            <?php else: ?>
            <li class="item empty"><!--  --> &nbsp;</li>
            <?php endif; ?>
        <?php endfor; ?>

    <?php endfor; ?>
    </ul>
</div>
<?php endif ?>
