<div class="faq ingredients clearfix">

		<div class="accordionButton">Organic Black Chia Seeds</div>
		<div class="accordionContent"><p><strong>INGREDIENTS</strong>: Organic Black Chia seeds</p><p><strong>Allergens</strong>: None</p><img src='http://numannadev.com/numanna/wp-content/uploads/2015/05/Organic-Black-Chia-Seeds.png' alt='' /></div>

		<div class="accordionButton">Classic Chili Mix</div>
		<div class="accordionContent"><p><strong>INGREDIENTS</strong>: Pre-cooked Pinto, Black &amp; Kidney Beans, Tomato Powder, Modified Food Starch, Dehydrated Vegetables (Onions, Red &amp; Green Bell Peppers), Spices, Sugar, Garlic Powder, Sea Salt, Honey Powder, Caramel, Onion Powder.</p>
<p><strong>Directions</strong> Bring 6 cups of water to boil. Slowly whisk in entire package of chili mix. Lower heat – simmer 20 -25 minutes at low boil, stirring occasionally. Add ½ lb. meat if desired.</p>
<p><strong>Allergens</strong>: None</p>
<p>Net Weights: 6 serv. = 10.6 ounces, 300 grams</p>
<img src='http://numannadev.com/numanna/wp-content/uploads/2015/05/Classic-Chili-Mix.png' class="nutripic" alt='' /></div>

		<div class="accordionButton">Granola</div>
		<div class="accordionContent"><p><strong>INGREDIENTS:</strong> Whole Rolled Oats, Milled Cane Sugar, Vegetable Oil (Canola Oil and/or Safflower and/or Sunflower Oil), Molasses, Coconut, Almonds, Sesame Seeds, Sunflower Seeds, Cashews, Walnuts, Honey, Salt, Natural Flavor, Cardamom Seed, Fennel Seed, Fenugreek Seed, Nutmeg.</p>
<p><strong>Directions</strong> Use as cereal, snack or trail mix.</p>
<p><strong>Allergens</strong>: Almonds, Cashews, Walnuts, Coconut</p>
<p>Net Weights: 6 serv. = 12 ounces, 342 grams</p>
<img src='http://numannadev.com/numanna/wp-content/uploads/2015/09/Granola.png' class="nutripic" alt='' /></div>

		<div class="accordionButton">Organic Spelt</div>
		<div class="accordionContent"><p><strong>INGREDIENTS:</strong> Organic Spelt</p><p><strong>Allergens</strong>: Wheat</p><img src='http://numannadev.com/numanna/wp-content/uploads/2015/09/Organic-Spelt.png' class="nutripic" alt='' /></div>

		<div class="accordionButton">Enchilada, Beans &amp; Rice</div>
		<div class="accordionContent"><p><strong>INGREDIENTS:</strong> Rice, Pre-cooked Pinto Beans, Modified Food Starch, Cheddar Cheese (Pasteurized Milk, Salt, Cheese Culture, Enzymes), Non-dairy Creamer (Maltodextrin, Palm Oil, Sodium Caseinate, Di-potassium Phosphate, Mono and Di-glycerides, Natural Flavor, Annatto Color), Sweet Whey, Dehydrated Vegetables (Corn, Onions, Tomatoes), Vegetarian Chicken Base (Maltodextrin, Hydrolyzed Corn Protein, Salt, Corn Starch, Cane Sugar, Onion Powder, Garlic Powder, Parsley, Spices, Turmeric, Silicon Dioxide), Onion Powder, Sea Salt, Spices, Natural Flavor, Garlic, Chili Lime Flavor (Salt, Citric Acid, Chili Pepper, Maltodextrin, Paprika, Silicon Dioxide, Natural Flavor), Citric Acid.</p>
<p><strong>Directions</strong> Bring 6 1/2 cups of water to boil. Slowly whisk in entire package of mix. Lower heat – simmer 15 minutes, uncovered, stirring often.</p>
<p><strong>Allergens:</strong> Milk</p>
<p>Net Weights 6 serv. = 13.1 ounces 372 grams</p>
<p>No Gluten * GMO Free * Uses Sea Salt</p>
<p>No MSG/I+G/AYE * No Trans Fat * Good Source of Fiber<br />
Low Cholesterol</p>
<img src='http://numannadev.com/numanna/wp-content/uploads/2015/09/Enchilada-Beans-and-Rice.png' class="nutripic" alt='' /></div>

		<div class="accordionButton">Pasta Primavera</div>
		<div class="accordionContent"><p><strong>INGREDIENTS:</strong>Pasta (Enriched Durum Semolina, Niacin, Ferrous Sulfate (Iron), Thiamine Mononitrate, Riboflavin, Folic Acid), Non-dairy Creamer (Maltodextrin, Palm Oil, Sodium Caseinate, Di-potassium Phosphate, Mono and Di-glycerides, Natural Butter Flavor, Annatto Color), Modified Food Starch, Cheddar Cheese Powder (Cheddar Cheese (Pasteurized Milk, Salt, Cheese Culture Enzymes) Salt, Lactic Acid, Natural Flavors (Silicon Dioxide, Disodium Phosphate)), Natural Cheese Powder, Mushroom Powder, Natural Flavor, Dehydrated Vegetables (Peas, Broccoli), Sea Salt, Lemon Powder, Garlic, Spices.</p>
<p><strong>Directions</strong> ****REMOVE OXYGEN ABSORBER AND DISCARD PRIOR TO COOKING****</p>
<p><strong>10 servings</strong> - :   Bring 10 cups of water to boil.  Slowly whisk in entire package of mix.<br />
<strong>Lower heat </strong>– simmer 15 – 18 minutes, stirring often.  Remove from heat.  Stir in 2 tablespoons Butter or Margarine.<br />
<strong>Serve.</strong></p>
<p>Allergens: Wheat, Milk Net Weights 10 serv. = 25.6 ounces 726 grams</p>
<p><strong>Vegetarian * Uses Sea Salt * No I+G/AYE * No Trans Fats * Low in Fat * Low in Cholesterol * GMO Free</strong></p>
<img src='http://numannadev.com/numanna/wp-content/uploads/2015/09/Pasta-Primavera.png' class="nutripic" alt='' /></div>

		<div class="accordionButton">No Gluten Pasta Primavera</div>
		<div class="accordionContent"><p><strong>INGREDIENTS:</strong> No Gluten Pasta (Corn Flour, Rice Flour, Pea Protein, Mona and Diglycerides), Tomato Powder, Modified Food Starch, Dehydrated Vegetables (Onions, Tomatoes, Green Bell Peppers), Sugar, Garlic, Sea Salt, Parsley, Natural Colors, Spices.</p>
<p><strong>Directions</strong> ****REMOVE OXYGEN ABSORBER AND DISCARD PRIOR TO COOKING*****</p>
<p><strong>10 servings</strong> - Bring 9 1/4 cups of water to boil. Slowly whisk in entire package of mix.<br />
<strong>Lower heat </strong>– simmer 15 - 20 minutes, stirring often.</p>
<p>Allergens: Milk Net Weights 10 serv. = 22.7 ounces 645 grams</p>
<p><strong>Vegetarian * Uses Sea Salt * No I+G/AYE * No Trans Fats * Low in Fat * No Cholesterol</strong></p>
<img src='http://numannadev.com/numanna/wp-content/uploads/2015/09/Gluten-Free-Pasta-Primavera.png' class="nutripic" alt='' /></div>

		<div class="accordionButton">Organic Quinoa</div>
		<div class="accordionContent"><p><strong>INGREDIENTS:</strong> Organic Quinoa</p><p><strong>Allergens</strong>None</p><img src='http://numannadev.com/numanna/wp-content/uploads/2015/09/Organic-Quinoa.png' class="nutripic" alt='' /></div>


		<div class="accordionButton">No Gluten Italian Pasta W/ Marinara</div>
		<div class="accordionContent"><p><strong>INGREDIENTS:</strong> No Gluten Pasta (Corn Flour, Rice Flour, Pea Protein, Mona and Diglycerides), Non-dairy Creamer (Maltodextrin, Palm Oil, Sodium Caseinate, Di-potassium Phosphate, Mono and Di-glycerides, Natural Butter Flavor, Annatto Color), Modified Food Starch, Cheddar Cheese Powder (Cheddar Cheese (Pasteurized Milk, Salt, Cheese Culture Enzymes) Salt, Lactic Acid, Natural Flavors (Silicon Dioxide, Disodium Phosphate)), Natural Cheese Powder, Mushroom Powder, Natural Flavor, Dehydrated Vegetables (Peas, Broccoli), Sea Salt, Lemon Powder, Garlic, Spices.</p>
<p><strong>Directions</strong> ****REMOVE OXYGEN ABSORBER AND DISCARD PRIOR TO COOKING*****</p>
<p><strong>Directions</strong>: Bring 10 cups of water to boil. Slowly whisk in entire package of mix.</p>
<p>Lower heat – simmer 15 – 18 minutes, stirring often. Remove from heat. Stir in 2 tablespoons Butter or Margarine. Serve.</p>
<p><strong>Allergens</strong>: Milk</p>
<p>Net Weights 10 serv. = 25.6 ounces 726 grams</p>
<p>Vegetarian * Uses Sea Salt * No I+G/AYE * No Trans Fats * Low in Cholesterol</p>
<img src='http://numannadev.com/numanna/wp-content/uploads/2015/09/Italian-Pasta-with-Marinara.png' class="nutripic" alt='' /></div>

		<div class="accordionButton">Sweet Habanero Chili</div>
		<div class="accordionContent"><p><strong>INGREDIENTS:</strong> Pre-cooked Pinto, Black &amp; Kidney Beans, Tomato Powder, Dehydrated Pineapple, Modified Food Starch, Dehydrated Vegetables (Onions, Red &amp; Green Bell Peppers), Spices, Sugar, Garlic Powder, Sea Salt, Honey Powder, Caramel, Onion Powder.</p>
<p><strong>Directions</strong> Bring 6 cups of water to boil. Slowly whisk in entire package of chili mix. Lower heat – simmer 20 -25 minutes at low boil, stirring occasionally. Add ½ lb. meat if desired.</p>
<img src='http://numannadev.com/numanna/wp-content/uploads/2015/09/Sweet-Habenero-Chili-with-Pineapple.png' alt='' /></div>

		<div class="accordionButton">Parboiled Rice</div>
		<div class="accordionContent"><p><strong>INGREDIENTS:</strong> Parboiled Rice</p><p><strong>Allergens</strong>None</p><img src='http://numannadev.com/numanna/wp-content/uploads/2015/09/Parboiled-White-Rice.png' class="nutripic" alt='' /></div>

		<div class="accordionButton">Black Bean Soup</div>
		<div class="accordionContent"><p><strong>INGREDIENTS:</strong> Pre-cooked Black Beans, Food Starch-Modified, Vegetarian Chicken Base (Maltodextrin, Salt, Hydrolyzed Corn Protein, Corn Starch, Sugar, Onion, Powder, Garlic Powder, Spices, Natural Flavors, Turmeric, Silicon Dioxide), Dehydrated Onions, Garlic, Natural Lime Juice, Cilantro, Spices, Sea Salt, Jalapeno Dices.</p>
<p><strong>Allergens:</strong> None</p>
<p><strong>10 servings</strong>Bring 10 cups of water to boil. Slowly whisk in entire package of mix. Lower heat – simmer 15 – 18 minutes, stirring often. Remove from heat. Stir in 2 tablespoons Butter or Margarine. Serve.<br />
Net Weights 6 servings = 8.4 oz. 239 grams</p>
<p>Vegetarian * GMO Free * Uses Sea Salt</p>
<p>No MSG/I+G/AYE * No Trans Fat * No Cholesterol</p>
<p>High in Fiber * Low in Fat * No Gluten</p>
<img src='http://numannadev.com/numanna/wp-content/uploads/2015/09/Black-Bean-Soup.png' class="nutripic" alt='' /></div>

		<div class="accordionButton">Cream of Rice Soup</div>
		<div class="accordionContent"><p><strong>INGREDIENTS:</strong> Rice, Non-dairy Creamer (Maltodextrin, Palm Oil, Sodium Caseinate, Di-potassium Phosphate, Mono and Di-glycerides, Natural Flavor, Annatto Color), Modified Food Starch, Vegetarian Chicken Base (Maltodextrin, Hydrolyzed Corn Protein, Salt, Corn Starch, Cane Sugar, Onion Powder, Garlic Powder, Parsley, Spices, Turmeric, Silicon Dioxide), Dehydrated Vegetables (Potatoes, Onions, Celery, Carrots, Tomatoes), Natural Flavor, Sugar, Sea Salt, Garlic, Spices.</p>
<p><strong>Directions</strong> Bring 10 cups of water to boil. Slowly whisk in entire package of soup mix. Lower heat – simmer 20 -25 minutes, stirring occasionally.</p>
<p><strong>Allergens</strong>: Milk</p>
<p>Net Weights 10 serv. = 13.1 ounces 373 grams</p>
<p>Uses Sea Salt * No I+G/AYE * GMO Free * No Trans Fats * No Cholesterol * Low in Fat</p>
<img src='http://numannadev.com/numanna/wp-content/uploads/2015/09/Rice-Pilaf-Mix.png' class="nutripic" alt='' /></div>

		<div class="accordionButton">Mac 'n Cheese</div>
		<div class="accordionContent"><p><strong>INGREDIENTS:</strong> Pasta (Enriched Durum Semolina, Niacin, Ferrous Sulfate (Iron), Thiamine Mononitrate, Riboflavin, Folic Acid), Non-dairy Creamer (Maltodextrin, Palm Oil, Sodium Caseinate, Di-potassium Phosphate, Mono and Di-glycerides, Natural Flavor, Annatto Color), Modified Food Starch, Cheddar Cheese Powder (Pasteurized Milk, Salt, Cheese Culture, Enzymes), Sweet Whey, Cheddar Cheese Powder (Organic Dextrose, Maltodextrin, Whey Solids, Organic Corn Starch, Salt, Silicon Dioxide, Guar Gum, Annatto, Turmeric), Sea Salt, Xanthan Gum, Natural Color, Natural Butter Flavor (Whey Solids, Enzyme Modified Butter, Maltodextrin, Salt, Dehydrated Butter, Guar Gum, Annatto, Turmeric), Sugar, Ascorbic Acid.</p>
<p><strong>Directions</strong><br />
6 servings – Bring 6 cups of water to boil. Slowly whisk in entire package of mix.</p>
<p>Lower heat – simmer 12 – 15 minutes uncovered, stirring occasionally.</p>
<p><strong>Allergens: </strong>Milk, Wheat</p>
<p>Net Weight 6 serv. = 16.7 ounces 474 grams</p>
<p>Vegetarian * Uses Sea Salt * No MSG/I+G/AYE</p>
<p>No Trans Fats * Low Cholesterol</p>
<p>GMO Free</p>
<img src='http://numannadev.com/numanna/wp-content/uploads/2015/09/MacNCheese.png' class="nutripic" alt='' /></div>

		<div class="accordionButton">Organic Brown Jasmine Rice</div>
		<div class="accordionContent"><p><strong>INGREDIENTS:</strong> Organic Brown Jasmine Rice</p><p><strong>Allergens</strong>None</p><img src='http://numannadev.com/numanna/wp-content/uploads/2015/09/Organic-Brown-Jasmin-Rice.png' class="nutripic" alt='' /></div>

		<div class="accordionButton">Hawaiian Sweet and Sour</div>
		<div class="accordionContent"><p><strong>INGREDIENTS:</strong> Pasta (Enriched Durum Semolina, Niacin, Ferrous Sulfate (Iron), Thiamine Mononitrate, Riboflavin, Folic Acid), Sugar, Vegetarian Chicken Base (Maltodextrin, Hydrolyzed Corn Protein, Salt, Corn Starch, Cane Sugar, Onion Powder, Garlic Powder, Parsley, Spices, Turmeric, Silicon Dioxide), Modified Food Starch, Dehydrated Fruits and Vegetables (Onion, Pineapple, Red and Green Bell Peppers, Mango), Garlic, Citric Acid, Natural Flavor, Sea Salt, Natural Color, Xanthan Gum, Spices.</p>
<p><strong>Directions</strong>Bring 6 cups of water to boil. Slowly whisk in entire package of mix. Lower heat – simmer 15 minutes, uncovered, stirring often.</p>
<p><strong>Allergens</strong>: Wheat</p>
<p>Net Weights 6 serv. = 12.2 ounces 346 grams</p>
<p>Vegetarian * Uses Sea Salt * No MSG/I+G/AYE</p>
<p>No Trans Fats * Low in Fat * No Cholesterol</p>
<p>GMO Free</p>
<img src='http://numannadev.com/numanna/wp-content/uploads/2015/09/Hawaiian-Sweet-and-Sour.png' class="nutripic" alt='' /></div>

		<div class="accordionButton">Potato Casserole</div>
		<div class="accordionContent"><p><strong>INGREDIENTS:</strong> Non-dairy Creamer (Maltodextrin, Palm Oil, Sodium Caseinate, Di-potassium Phosphate, Mono and Di-glycerides, Natural Flavor, Annatto Color), Dehydrated Vegetables (Potatoes, Onions, Chives), Food Starch, Vegetarian Chicken Base (Maltodextrin, Hydrolyzed Corn Protein, Salt, Corn Starch, Cane Sugar, Onion Powder, Garlic Powder, Parsley, Spices, Turmeric, Silicon Dioxide), Cheddar Cheese Powder (Cheddar Cheese (Pasteurized Milk, Salt, Cheese Culture Enzymes), Salt, Lactic Acid, Natural Flavors), Sweet Whey, Natural Butter Powder (Whey Solids, Enzyme-Modified Butter, Maltodextrin, Salt, Dehydrated Butter, Guar Gum, Annatto and Turmeric), Natural Flavor, Bleu Cheese Powder (Pasturized Milk, Salt, Cheese Culture, Enzymes), Cheese Powder (Dextrose, Maltodextrin, Whey Solids, Corn Starch, Silicon Dioxide, Salt, Guar Gum, Natural Color), Sea Salt, Onion Powder, Spices</p>
<p><strong>Directions</strong> ****REMOVE OXYGEN ABSORBER AND DISCARD AFTER OPENING*****</p>
<p><strong>10 servings: </strong>Bring 10 cups of water to boil. Slowly whisk in entire package of mix. Lower heat – simmer 15 – 18 minutes, stirring often. Remove from heat. Stir in 2 tablespoons Butter or Margarine. Serve.</p>
<p><strong>Allergens:</strong> Milk</p>
<img src='http://numannadev.com/numanna/wp-content/uploads/2015/09/Potato-Casserole.png' class="nutripic" alt='' /></div>

		<div class="accordionButton">Organic Sprouting Seeds</div>
		<div class="accordionContent"><p><strong>INGREDIENTS:</strong> Organic Mung beans and Organic Adzuki beans.</p>
<p><strong>Directions</strong>Soak desired amount of seeds in water overnight. In morning rinse and let drain. For the next few days soak in water for 1 min and drain. Seeds will begin to sprout. When they are 2-3 inches long they are at peak nutritional value and can be used as desired.</p></div>

		<div class="accordionButton">Rice Pilaf</div>
		<div class="accordionContent"><p><strong>INGREDIENTS:</strong> Rice, Vegetarian Chicken Base (Maltodextrin, Hydrolyzed Corn Protein, Salt, Corn Starch, Cane Sugar, Onion Powder, Garlic Powder, Parsley, Spices, Turmeric, Silicon Dioxide), Pasta (Enriched Durum Semolina, Niacin, Ferrous Sulfate (Iron), Thiamine Mono-nitrate, Riboflavin, Folic Acid), Dehydrated Onions, Sea Salt, Garlic, Natural Butter Flavor (Whey Solids, Enzyme Modified Butter, Maltodextrin, Salt, Dehydrated Butter, Guar Gum, Annatto, Turmeric), Spices.</p>
<p><strong>Directions</strong> ****REMOVE OXYGEN ABSORBER AND DISCARD PRIOR TO COOKING*****<br />
In large skillet combine contents of package with 4 tablespoons butter or margarine and ½ cup water – cook mixture until golden brown. Add 3.5 cups of water, mix well, cover. Cook for additional 15 – 20 minutes – stirring often.</p>
<p><strong>10 servings</strong>Bring 10 cups of water to boil. Slowly whisk in entire package of mix. Lower heat – simmer 15 – 18 minutes, stirring often. Remove from heat. Stir in 2 tablespoons Butter or Margarine. Serve.<br />
<strong>Allergens</strong>: Wheat, Dairy</p>
<p>Net Weights: 6 serv. = 14.6 ounces, 415 grams</p>
<p>Uses Sea Salt * No I+G/AYE * GMO Free * No Trans Fats * Low in Fat * No Cholesterol</p>
<img src='http://numannadev.com/numanna/wp-content/uploads/2015/09/Rice-Pilaf-Mix.png' class="nutripic" alt='' /></div>

		<div class="accordionButton">Italian Pasta W/ Marinara</div>
		<div class="accordionContent"><p><strong>INGREDIENTS:</strong> Pasta (Enriched Durum Semolina, Niacin, Ferrous Sulfate (Iron), Thiamine Mononitrate, Riboflavin, Folic Acid), Tomato Powder, Modified Food Starch, Dehydrated Vegetables (Onions, Tomatoes, Green Bell Peppers), Sugar, Garlic, Sea Salt, Parsley, Natural Colors, Spices.</p>
<p><strong>Directions</strong> 6 servings – Bring 5.5 cups of water to boil.<br />
Slowly whisk in entire package of mix.</p>
<p>Lower heat – simmer 15 – 20 minutes, stirring often.</p>
<p><strong>Allergens</strong>: Wheat</p>
<p>Net Weights 6 serv. = 13.6 ounces 387 grams</p>
<p>Vegetarian * Uses Sea Salt * No MSG/I+F/AYE</p>
<p>GMO Free * No Trans Fats * Low in Fat</p>
<p>No Cholesterol * Good Source of Fiber</p>
<img src='http://numannadev.com/numanna/wp-content/uploads/2015/09/Italian-Pasta-with-Marinara.png' class="nutripic" alt='' /></div>

		<div class="accordionButton">Oatmeal Brown Sugar</div>
		<div class="accordionContent"><p><strong>INGREDIENTS:</strong> Oats, Sugar, Molasses solids, Sea Salt.</p>
<p><strong>Directions</strong>Bring 1 cup of water to boil. Stir in ½ cup Oatmeal. Cook 1 minute, stirring occasionally. Let stand 1 minute. Serve</p>
<p><strong>Allergens</strong>: None</p>
<p>Net Weights 6 serv. = 9.5 ounces 270 grams</p>
<p>Vegetarian * No Gluten * GMO Free</p>
<p>No MSG/I+G/AYE * No Trans Fats * Low in Fat</p>
<p>No Cholesterol * Good Source of Fiber</p>
<img src='http://numannadev.com/numanna/wp-content/uploads/2015/09/Oatmeal-with-Brown-Sugar.png' class="nutripic" alt='' /></div>

		<div class="accordionButton">Cheesy Potato Soup</div>
		<div class="accordionContent"><p><strong>INGREDIENTS:</strong> Non-dairy Creamer (Maltodextrin, Palm Oil, Sodium Caseinate, Di-potassium Phosphate, Mono and Di-glycerides, Natural Flavor, Annatto Color), Dehydrated Vegetables (Potatoes, Onions, Carrot), Modified Food Starch, White Cheddar Cheese (Cheddar Cheese (pasteurized milk, salt, cheese culture, enzymes), Salt, Lactic Acid, Natural Flavors), Vegetarian Chicken Base (Maltodextrin, Hydrolyzed Corn Protein, Salt, Corn Starch, Cane Sugar, Onion Powder, Garlic Powder, Parsley, Spices, Turmeric, Silicon Dioxide), Sweet Whey, Natural Butter Flavor (Whey Solids, Enzyme Modified Butter, Maltodextrin, Salt, Dehydrated Butter, Guar Gum, Annatto, Turmeric), Spices, Sea Salt.</p>
<p><strong>Directions</strong> Bring 6 cups of water to boil. Slowly whisk in entire package of soup mix. Lower heat – simmer 20 -25 minutes, stirring occasionally.</p>
<p><strong>Allergens</strong>: Milk</p>
<p>Net Weights 6 serv. = 9.5 ounces 270 grams * Vegetarian * Uses Sea Salt</p>
<p>No Gluten * GMO Free * No MSG/I+G/AYE * No Trans Fats<br />
Low in Cholesterol</p>
<img src='http://numannadev.com/numanna/wp-content/uploads/2015/09/Cheesy-Potato-Soup.png' class="nutripic" alt='' /></div>

		<div class="accordionButton">Pasta Alfredo</div>
		<div class="accordionContent"><p><strong>INGREDIENTS: </strong>Pasta (Enriched Durum Semolina, Niacin, Ferrous Sulfate (Iron), Thiamine Mononitrate, Riboflavin, Folic Acid), Non-dairy Creamer (Maltodextrin, Palm Oil, Sodium Caseinate, Di-potassium Phosphate, Mono and Di-glycerides, Natural Flavor, Annatto Color), Cheddar Cheese Powder (Cheddar Cheese (Pasteurized Milk, Salt, Cheese Culture Enzymes), Salt, Lactic Acid, Natural Flavors), Modified Food Starch, Sweet Whey, Mushroom Powder, Natural Flavor, Sea Salt, Garlic, Spices.</p>
<p><strong>Directions</strong> Bring 6 cups of water to boil. Slowly whisk in entire package of mix . Lower heat – simmer 15 minutes, stirring often. Remove from heat. Stir in 2 tablespoons Butter or Margarine. Serve.<br />
Allergens: Wheat, Milk<br />
Net Weights 6 serv. = 13.6 ounces 385 grams<br />
Vegetarian * GMO Free * Uses Sea Salt<br />
No MSG/I+G/AYE * No Trans Fats<br />
Low Cholesterol</p>
<img src='http://numannadev.com/numanna/wp-content/uploads/2015/09/Pasta-Alfredo.png' class="nutripic" alt='' /></div>

		<div class="accordionButton">Pancake Mix</div>
		<div class="accordionContent"><p><strong>INGREDIENTS:</strong> Flour (bleached wheat flour, niacin, reduced iron, thiamine mononitrate, riboflavin, folic acid), Non-fat Dry Milk, Sugar, Baking Powder, Whole Eggs (whole eggs, sodium silicoalluminate (an anticaking agent)), Sea Salt.</p>
<p><strong>Directions</strong> Add 1 1/4 cups mix to 1 cup cold water and 2 TBS oil – mix. Add more water until desired consistency is reached. Pre-heat oiled skillet/griddle to 375 degrees F. Cook pancakes 1 – 1 ½ minutes per side until golden brown.</p>
<p><strong>Allergens</strong>: Wheat, Milk, Eggs</p>
<p>Net Weights: 6 serv. = 14.1 ounces, 400 grams</p>
<p>Vegetarian * Uses Sea Salt * No MSG/I+G/AYE * No Trans Fats * Low in Fat * GMO Free</p>
<img src='http://numannadev.com/numanna/wp-content/uploads/2015/09/Pancake-Mix.png' class="nutripic" alt='' /></div>

		<div class="accordionButton">Cheddar Broccoli Soup</div>
		<div class="accordionContent"><p><strong>INGREDIENTS:</strong> Non-dairy Creamer (Maltodextrin, Palm Oil, Sodium Caseinate, Di-potassium Phosphate, Mono and Di-glycerides, Natural Flavor, Annatto Color), Modified Food Starch, Sweet Whey, Dehydrated Vegetables (Onions, Broccoli), Cheddar Cheese Powder (Cheddar Cheese (Pasteurized Milk, Salt, Cheese Culture Enzymes), Salt, Lactic Acid, Natural Flavors), Cheddar Cheese Powder (Pasteurized Milk, Salt, Cheese Culture, Enzymes), Vegetarian Chicken Base (Maltodextrin, Hydrolyzed Corn Protein, Salt, Corn Starch, Cane Sugar, Onion Powder, Garlic Powder, Parsley, Spices, Turmeric, Silicon Dioxide), Sea Salt, Cheddar Cheese Powder (Organic Dextrose, Maltodextrin, Whey Solids, Organic Corn Starch, Salt, Silicon Dioxide, Guar Gum, Annatto, Turmeric), Xanthan Gum, Spices, Natural Butter Flavor (Whey Solids, Enzyme Modified Butter, Maltodextrin, Salt, Dehydrated Butter, Guar Gum, Annatto, Turmeric), Natural Color, Sugar, Ascorbic Acid.</p>
<p><strong>Directions</strong> Bring 6 cups of water to boil. Slowly whisk in entire package of soup mix. Lower heat – simmer 10 -15 minutes, stirring occasionally.</p>
<p><strong>Allergens</strong>: Milk</p>
<p>Net Weight 6 serv. = 7.0 ounces 200 grams * Uses Sea Salt * No Gluten</p>
<p>GMO Free * No MSG/I+G/AYE * No Trans Fats * Low in Cholesterol</p>
<img src='http://numannadev.com/numanna/wp-content/uploads/2015/09/Cheddar-Brocolli-Soup.png' class="nutripic" alt='' /></div>

        <br class="clear"/>
        <br/><br/>

</div>