<div class="row" id="browser">
    <div class="span12">

        <!--
        <div id="image-selection">
            <div class="choose">
                <p>Choose your image by search or the below categories.</p>
                <span>or check out the</span>
                <a href="http://wallawall.com/managecategory" title="Walla Artists Gallery">Walla Artists Gallery</a>
                <span>or</span>
                <a href="http://wallawall.com/uploadproduct/">Upload Your Own Image</a>
            </div>
        </div>
        -->
        <div class="searchform">
            <form class="container form-search">
                <div class="label">Step 1:</div>
                <input type="text" class="search-query span4" value="Find the perfect image..." onfocus="if(this.value==this.defaultValue)this.value='';" onblur="if(this.value=='')this.value=this.defaultValue;"/>
                <button type="submit" class="btn btn-primary">Search</button>
                <div class="options">
                    <a href="#">Walla Artists Gallery</a>
                    <a href="<?php echo $this->getUrl('') ?>/details">Upload Your Own Image</a>
                </div>
            </form>
        </div>
        <div id="category-container">
            <div class="categories-list" id="category-holder">
                <div class="bread center">
                    <div class="breadcrumbs">
                    <ul>
                        <li class="home">
                            <a title="Go to Home Page" href="http://127.0.0.1/walla/">Home</a>
                        <span>/ </span>
                        </li>
                        <li class="cms_page">
                            <strong>Textures</strong>
                        </li>
                    </ul>
                    </div>
                </div>
                <h1 class="center">Choose Your Wall Image</h1>
                <br/><br/>
                <ul class="thumbnails" id="categoryitems">
                    <li class="li-page1">
                        <a href="/details" title="Animals" class="thumbnail"><img src="<?php echo $this->getSkinUrl(); ?>images/misc/m2.png" alt="Animals"/></a>
                        <span class="cat-name">
                            <a href="<?php echo $this->getUrl('') ?>/details" title="Abstract">Dorem Photo</a>
                        </span>
                    </li>
                    <li class="li-page1">
                        <a href="<?php echo $this->getUrl('') ?>/details" title="Animals" class="thumbnail"><img src="http://static1.bigstockphoto.com/thumbs/4/3/9/small3/93419801.jpg" alt="Animals"/></a>
                        <span class="cat-name">
                            <a href="<?php echo $this->getUrl('') ?>/details" title="Abstract">Dorem Photo</a>
                        </span>
                    </li>
                    <li class="li-page1">
                        <a href="<?php echo $this->getUrl('') ?>/details" title="Animals" class="thumbnail"><img src="http://static8.bigstockphoto.com/thumbs/7/3/1/small3/137522948.jpg" alt="Animals"/></a>
                        <span class="cat-name">
                            <a href="<?php echo $this->getUrl('') ?>/details" title="Abstract">Dorem Photo</a>
                        </span>
                    </li>
                    <li class="li-page1">
                        <a href="<?php echo $this->getUrl('') ?>/details" title="Animals" class="thumbnail"><img src="http://static1.bigstockphoto.com/thumbs/4/3/9/small3/93419801.jpg" alt="Animals"/></a>
                        <span class="cat-name">
                            <a href="<?php echo $this->getUrl('') ?>/details" title="Abstract">Dorem Photo</a>
                        </span>
                    </li>
                    <li class="li-page1">
                        <a href="<?php echo $this->getUrl('') ?>/details" title="Animals" class="thumbnail"><img src="http://static8.bigstockphoto.com/thumbs/7/3/1/small3/137522948.jpg" alt="Animals"/></a>
                        <span class="cat-name">
                            <a href="<?php echo $this->getUrl('') ?>/details" title="Abstract">Dorem Photo</a>
                        </span>
                    </li>
                    <li class="li-page1">
                        <a href="<?php echo $this->getUrl('') ?>/details" title="Animals" class="thumbnail"><img src="<?php echo $this->getSkinUrl(); ?>images/misc/m2.png" alt="Animals"/></a>
                        <span class="cat-name">
                            <a href="<?php echo $this->getUrl('') ?>/details" title="Abstract">Dorem Photo</a>
                        </span>
                    </li>
                    <li class="li-page1">
                        <a href="<?php echo $this->getUrl('') ?>/details" title="Animals" class="thumbnail"><img src="<?php echo $this->getSkinUrl(); ?>images/misc/m1.png" alt="Animals"/></a>
                        <span class="cat-name">
                            <a href="<?php echo $this->getUrl('') ?>/details" title="Abstract">Dorem Photo</a>
                        </span>
                    </li>
                    <li class="li-page1">
                        <a href="<?php echo $this->getUrl('') ?>/details" title="Animals" class="thumbnail"><img src="<?php echo $this->getSkinUrl(); ?>images/misc/m2.png" alt="Animals"/></a>
                        <span class="cat-name">
                            <a href="<?php echo $this->getUrl('') ?>/details" title="Abstract">Dorem Photo</a>
                        </span>
                    </li>
                    <li class="li-page1">
                        <a href="<?php echo $this->getUrl('') ?>/details" title="Animals" class="thumbnail"><img src="http://static8.bigstockphoto.com/thumbs/7/3/1/small3/137522948.jpg" alt="Animals"/></a>
                        <span class="cat-name">
                            <a href="<?php echo $this->getUrl('') ?>/details" title="Abstract">Dorem Photo</a>
                        </span>
                    </li>
                    <li class="li-page1">
                        <a href="<?php echo $this->getUrl('') ?>/details" title="Animals" class="thumbnail"><img src="http://static1.bigstockphoto.com/thumbs/4/3/9/small3/93419801.jpg" alt="Animals"/></a>
                        <span class="cat-name">
                            <a href="<?php echo $this->getUrl('') ?>/details" title="Abstract">Dorem Photo</a>
                        </span>
                    </li>
                    <li class="li-page1">
                        <a href="<?php echo $this->getUrl('') ?>/details" title="Animals" class="thumbnail"><img src="http://static8.bigstockphoto.com/thumbs/7/3/1/small3/137522948.jpg" alt="Animals"/></a>
                        <span class="cat-name">
                            <a href="<?php echo $this->getUrl('') ?>/details" title="Abstract">Dorem Photo</a>
                        </span>
                    </li>
                    <li class="li-page1">
                        <a href="<?php echo $this->getUrl('') ?>/details" title="Animals" class="thumbnail"><img src="http://static1.bigstockphoto.com/thumbs/4/3/9/small3/93419801.jpg" alt="Animals"/></a>
                        <span class="cat-name">
                            <a href="<?php echo $this->getUrl('') ?>/details" title="Abstract">Dorem Photo</a>
                        </span>
                    </li>

                </ul>
            </div>
        </div>

    </div>
</div>