
<?php
/**
 * Product view template
 *
 * @see Mage_Catalog_Block_Product_View
 * @see Mage_Review_Block_Product_View
 */
?>
<?php $_helper = $this->helper('catalog/output'); ?>
<?php $_product = $this->getProduct(); ?>
<script type="text/javascript">
    var optionsPrice = new Product.OptionsPrice(<?php echo $this->getJsonConfig() ?>);
</script>
<div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
<div class="product-view">
    <div class="product-essential">
    <form action="<?php echo $this->getSubmitUrl($_product) ?>" method="post" id="product_addtocart_form"<?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
        <div class="no-display">
            <input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />
            <input type="hidden" name="related_product" id="related-products-field" value="" />
        </div>

         <!--<div class="left bread"><?php  echo $this->getLayout()->getBlock("breadcrumbs")->toHtml()?></div>
         <div class="right sku">SKU: <?php echo $this->htmlEscape($_product->getSku()) ?></div>
         <div class="clear"></div>-->

        <div class="product-img-box">
          <div class="inner" style="position:relative;">
              <?php echo $this->getChildHtml('media') ?>
          </div>
        </div>

        <div class="product-shop">
            <div class="product-name">
                <h1><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></h1>
            </div>

            <div class="under-name clearfix">
                <div class="review-cell">
                    <?php echo $this->getReviewsSummaryHtml($_product, false, true)?>
                </div>
                <div class="the-links">
                  <?php if ($this->canEmailToFriend()): ?>
                      <p class="email-friend"><a href="<?php echo $this->helper('catalog/product')->getEmailToFriendUrl($_product) ?>"><?php echo $this->__('Email a Friend') ?></a></p>
                  <?php endif; ?>
                </div>
                <div class="clear"></div>
                <div class="sku">SKU: <?php echo $this->htmlEscape($_product->getSku()) ?></div>
            </div>

            <?php echo $this->getChildHtml('alert_urls') ?>
            <div class="top-prices">
                <?php echo $this->getChildHtml('product_type_data') ?>
            </div>
            <?php echo $this->getTierPriceHtml() ?>
            <?php echo $this->getChildHtml('extrahint') ?>



            <?php if ($_product->getDescription()):?>
                <div class="short-description">
                    <div class="std"><?php echo $_helper->productAttribute($_product, $_product->getDescription(), 'description') ?></div>
                      <br/>
                      <!-- Go to www.addthis.com/dashboard to customize your tools -->
                      <script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-4e69277b21bd7183" async="async"></script>
                      <!-- Go to www.addthis.com/dashboard to customize your tools -->
                      <div class="addthis_sharing_toolbox"></div>

                </div>
            <?php endif;?>

            <?php echo $this->getChildHtml('other');?>


            <?php if (!$this->hasOptions()):?>
                <div class="add-to-box no-options <?php if ($_product->getTypeId() == Mage_Catalog_Model_Product_Type::TYPE_GROUPED) { ?>grouped-options<?php } ?> ">
                    <?php if($_product->isSaleable()): ?>
                        <?php echo $this->getPriceHtml($_product, true) ?>
                        <?php echo $this->getChildHtml('addtocart') ?>
                        <div class="clear"></div>
                        <?php echo $this->getChildHtml('addto') ?>
                    <?php endif; ?>
                </div>
                <?php echo $this->getChildHtml('extra_buttons') ?>
            <?php elseif (!$_product->isSaleable()): ?>
                <div class="add-to-box">
                    <?php echo $this->getChildHtml('addto') ?>
                </div>
            <?php endif; ?>

            <?php if ($_product->isSaleable() && $this->hasOptions()):?>
                <?php echo $this->getChildChildHtml('container1', '', true, true) ?>
            <?php endif;?>

            <?php if ($_product->isSaleable() && $this->hasOptions()):?>
                <?php echo $this->getChildChildHtml('container2', '', true, true) ?>
            <?php endif;?>


        </div>


        <div class="clear"></div>


    </form>
    <script type="text/javascript">
    //<![CDATA[
        var productAddToCartForm = new VarienForm('product_addtocart_form');
        productAddToCartForm.submit = function(button, url) {
            if (this.validator.validate()) {
                var form = this.form;
                var oldUrl = form.action;

                if (url) {
                   form.action = url;
                }
                var e = null;
                try {
                    this.form.submit();
                } catch (e) {
                }
                this.form.action = oldUrl;
                if (e) {
                    throw e;
                }

                if (button && button != 'undefined') {
                    button.disabled = true;
                }
            }
        }.bind(productAddToCartForm);

        productAddToCartForm.submitLight = function(button, url){
            if(this.validator) {
                var nv = Validation.methods;
                delete Validation.methods['required-entry'];
                delete Validation.methods['validate-one-required'];
                delete Validation.methods['validate-one-required-by-name'];
                // Remove custom datetime validators
                for (var methodName in Validation.methods) {
                    if (methodName.match(/^validate-datetime-.*/i)) {
                        delete Validation.methods[methodName];
                    }
                }

                if (this.validator.validate()) {
                    if (url) {
                        this.form.action = url;
                    }
                    this.form.submit();
                }
                Object.extend(Validation.methods, nv);
            }
        }.bind(productAddToCartForm);
    //]]>
    </script>
    </div>

    <div class="product-collateral">
        <?php echo $this->getChildHtml('info_tabs') ?>
        <?php echo $this->getChildHtml('upsell_products') ?>
        <?php echo $this->getChildHtml('product_additional_data') ?>

    </div>
</div>
