<!--@subject [ZohoCRM Free Edition]: ZohoCRM User's License Limited @-->

<style type="text/css">
    body,td { color:#2f2f2f; font:11px/1.35em Verdana, Arial, Helvetica, sans-serif; }
</style>

<div style="font:11px/1.35em Verdana, Arial, Helvetica, sans-serif;">
    <table cellspacing="0" cellpadding="0" border="0" width="98%" style="margin-top:10px; font:11px/1.35em Verdana, Arial, Helvetica, sans-serif; margin-bottom:10px;">
        <tr>
            <td align="center" valign="top">
                <!-- [ header starts here] -->
                <table cellspacing="0" cellpadding="0" border="0" width="650">
                    <tr>
                        <td valign="top">
                            <p><a href="{{store url=""}}" style="color:#1E7EC8;"><img src="{{skin url="images/logo_email.gif" _area='frontend'}}" alt="Magento" border="0"/></a></p></td>
                    </tr>
                </table>

                <!-- [ middle starts here] -->
                <table cellspacing="0" cellpadding="0" border="0" width="650">
                    <tr>
                        <td valign="top">
                            <p><strong>Dear, {{htmlescape var=$user.name}}</strong>,<br/>
                                The License of current zoho user "{{htmlescape var=$old_zoho_username}}" is Limited.</p>
                            {{depend autochange}}
                            <p>
                                Zoho Account of extension ZohoCRM Free Edition has been changed to username "{{htmlescape var=$new_zoho_username}}".
                            </p>
                            {{/depend}}

                            <p>Best regards,<br/><strong>{{var store.getFrontendName()}}</strong></p>

                        </td>
                    </tr>
                </table>

            </td>
        </tr>
    </table>
</div>