<?php
/**
 * 
 * @category   CRM4Ecommerce
 * @package    CRM4Ecommerce_ZohoSynchronization
 * @author     Philip Nguyen <philip@crm4ecommerce.com>
 * @link       http://crm4ecommerce.com
 * @see        CRM4Ecommerce_ZohoSynchronization_Block_Adminhtml_Mapping_Form_New
 */
?>
<div class="entry-edit collapseable">
    <form method="post" action="<?php echo $this->getSaveUrl();?>">
        <input name="c_action" type="hidden" value="<?php echo Mage::registry('c_action');?>" />
        <input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey();?>" />
    <div class="entry-edit-head collapseable">
        <a id="crm4ecommerce_zohosynchronization_contact_params-head" class="open" onclick="Fieldset.toggleCollapse('crm4ecommerce_zohosynchronization_contact_params'); return false;" href="#">
            <?php echo $this->__('Zoho Contact Settings'); ?>
        </a>
    </div>
    <fieldset id="crm4ecommerce_zohosynchronization_contact_params" style="" class="config collapseable">
        <legend><?php echo $this->__('Zoho Contact Settings'); ?></legend>
        <table cellspacing="0" class="form-list" style="width: 100%;">
            <tbody>
                <tr>
                    <td class="label" style="width: 120px;"><label style="width: 120px; padding-right: 0px" for="config[contact_duplicate_insert]"><?php echo $this->__('Duplicate Insert') ?></label></td>
                    <td class="value">
                        <select class="input-text" id="config[contact_duplicate_insert]" name="config[contact_duplicate_insert]" style="width: 97%"><?php
                            $zohoDuplicateChecks = Mage::getModel('zohosynchronization/array_zohoDuplicateCheck')->toOptionArray();
                            foreach ($zohoDuplicateChecks as $key => $value) { ?>
                                <option value="<?php echo $key;?>" <?php echo Mage::getStoreConfig('crm4ecommerce_zohosynchronization/params/contact_duplicate_insert') == $key ? 'selected="selected"' : ''; ?>><?php echo $value;?></option>
                            <?php
                            }
                        ?>
                        </select>
                        <p class="note" style="width: 97%;">
                            <span><?php echo $this->__('Zoho Contact has key field is <b>Email</b>.');?></span>
                        </p>
                    </td>
                </tr>
                <tr>
                    <td class="label" style="width: 120px;"><label style="width: 120px; padding-right: 0px" for="config[contact_only_sync_billing_address]"><?php echo $this->__("Only Sync Customer's Billing Address") ?></label></td>
                    <td class="value">
                        <select class="input-text" id="config[contact_only_sync_billing_address]" name="config[contact_only_sync_billing_address]" style="width: 97%">
                            <option value="1" <?php echo Mage::getStoreConfig('crm4ecommerce_zohosynchronization/params/contact_only_sync_billing_address') == '1' ? 'selected="selected"' : ''; ?>><?php echo $this->__('Yes');?></option>
                            <option value="0" <?php echo Mage::getStoreConfig('crm4ecommerce_zohosynchronization/params/contact_only_sync_billing_address') == '0' ? 'selected="selected"' : ''; ?>><?php echo $this->__('No');?></option>
                        ?>
                        </select>
                        <p class="note" style="width: 97%;">
                            <span><?php echo $this->__('If this value is Yes, system will only synchronize default billing address of customers, billing address of guests into zohocrm contact.');?></span>
                        </p>
                    </td>
                </tr>
                <tr>
                    <td class="label" colspan="2"><b><?php echo $this->__("When customer's addresses are deleted") ?>:</b></td>
                </tr>
                <tr>
                    <td class="label" style="width: 120px;"><label style="width: 120px; padding-right: 0px" for="config[contact_allow_delete]"><?php echo $this->__('Allow Delete Contact in ZohoCRM') ?></label></td>
                    <td class="value">
                        <select class="input-text" id="config[contact_allow_delete]" name="config[contact_allow_delete]" style="width: 97%">
                            <option value="1" <?php echo Mage::getStoreConfig('crm4ecommerce_zohosynchronization/params/contact_allow_delete') == '1' ? 'selected="selected"' : ''; ?>><?php echo $this->__('Yes');?></option>
                            <option value="0" <?php echo Mage::getStoreConfig('crm4ecommerce_zohosynchronization/params/contact_allow_delete') == '0' ? 'selected="selected"' : ''; ?>><?php echo $this->__('No');?></option>
                        ?>
                        </select>
                        <p class="note" style="width: 97%;">
                            <span><?php echo $this->__('Allow delete corresponding contact in ZohoCRM when customer is deleted or not.');?></span>
                        </p>
                    </td>
                </tr>
                <?php if (Mage::getStoreConfig('crm4ecommerce_zohosynchronization/params/contact_allow_delete') == '0') { ?>
                <tr>
                    <td class="label" style="width: 120px;"><label style="width: 120px; padding-right: 0px" for="config[contact_update_field]"><?php echo $this->__('Update field') ?></label></td>
                    <td class="value">
                        <table cellpadding="0" cellspacing="0" border="0" width="97%"><tr>
                                <td style="width: 203px;">
                        <?php 
                            $options = Mage::getStoreConfig('crm4ecommerce_zohosynchronization/mapping_fields/logs/Contacts');
                            $group_options = explode('@@', $options);
                        ?>
                        <select class="input-text" id="config[contact_update_field]" name="config[contact_update_field]" style="width: 200px">
                            <option value=""><?php echo $this->__('None'); ?></option>
                            <?php
                                foreach ($group_options as $group_option) {
                                    $group_option = explode('@', $group_option);
                                    if (count($group_option) > 1) {
                                ?>
                                <optgroup label="<?php echo $group_option[0];?>">
                                <?php
                                    $options = explode(';', $group_option[1]);
                                    foreach ($options as $option) {
                                        $option = explode(',', $option);
                                        if (count($option) == 3) {
                                    ?>
                                    <option <?php echo (Mage::getStoreConfig('crm4ecommerce_zohosynchronization/params/contact_update_field') == $option[0]) ? 'selected="true"' : ''; ?> value="<?php echo $option[0];?>"><?php echo $option[1];?></option>
                                    <?php
                                        }
                                    } ?>
                                </optgroup>
                                <?php }
                                }
                            ?>
                        </select>
                                </td>
                                <td style="width: 18px; text-align: center;"><?php echo $this->__('is');?></td>
                        <td>
                            <input type="text" class="input-text" name="config[contact_update_field_value]" style="width: 100%;" value="<?php echo Mage::getStoreConfig('crm4ecommerce_zohosynchronization/params/contact_update_field_value');?>" />
                        </td></tr></table>
                    </td>
                </tr>
                <?php } ?>
            </tbody>
        </table>
        <div style="text-align: right; margin-top: 5px; padding-top: 10px; border-top: 2px solid #CCCCCC;">        
            <table style="width: 100%;"><tr><td>                    
                <button name="submit" value="save" class="scalable save" style="" type="submit">
                    <span><span><span><?php echo $this->__('Save');?></span></span></span>
                </button></td></tr>
            </table>
        </div>
    </fieldset>
    <script type="text/javascript">
        Fieldset.applyCollapse('crm4ecommerce_zohosynchronization_contact_params');
    </script>
    </form>
</div>