
<?php $_product = $this->getProduct(); ?>
<?php $_wishlistSubmitUrl = $this->helper('wishlist')->getAddUrl($_product); ?>
<?php $buttonTitle = $this->__('Add to Cart'); ?>

<?php if($_product->isSaleable()): ?>
    <div class="add-to-cart">
        <?php if(!$_product->isGrouped()): ?>
            <label for="qty"><?php echo $this->__('Qty:') ?></label>
            <input type="text" name="qty" id="qty" maxlength="12" value="<?php echo $this->getProductDefaultQty() * 1 ?>" title="<?php echo $this->__('Qty') ?>" class="input-text qty" />
        <?php endif; ?>

        <button type="button" title="<?php echo $buttonTitle ?>" class="btn btn-primary" onclick="productAddToCartForm.submit(this)"><?php echo $buttonTitle ?><span class="img"><!--  --></span></button>

        <?php echo $this->getChildHtml('', true, true) ?>
    </div>
<?php endif; ?>
