<div class="box-collateral box-up-sell videos">
<h2><?php echo $this->__('Product Videos') ?></h2>
<ul class="products-grid grid-upsell" id="video-product-table">
    <li class="item">
        <a href="#modal-video1" data-toggle="modal"><img src="<?php echo $this->getSkinUrl(); ?>images/misc/video.png"alt=""></a>
        <h3 class="product-name"><a href="#modal-video1" data-toggle="modal">Video Name</a></h3>
    </li>
    <li class="item">
        <a href="#modal-video2" data-toggle="modal"><img src="<?php echo $this->getSkinUrl(); ?>images/misc/video.png"alt=""></a>
        <h3 class="product-name"><a href="#modal-video2" data-toggle="modal">Video Name</a></h3>
    </li>
    <li class="item">
        <a href="#modal-video3" data-toggle="modal"><img src="<?php echo $this->getSkinUrl(); ?>images/misc/video.png"alt=""></a>
        <h3 class="product-name"><a href="#modal-video3" data-toggle="modal">Video Name</a></h3>
    </li>
    <li class="item">
        <a href="#modal-video4" data-toggle="modal"><img src="<?php echo $this->getSkinUrl(); ?>images/misc/video.png"alt=""></a>
        <h3 class="product-name"><a href="#modal-video4" data-toggle="modal">Video Name</a></h3>
    </li>
    <li class="item">
        <a href="#modal-video5" data-toggle="modal"><img src="<?php echo $this->getSkinUrl(); ?>images/misc/video.png"alt=""></a>
        <h3 class="product-name"><a href="#modal-video5" data-toggle="modal">Video Name</a></h3>
    </li>
</ul>
            <div id="modal-video1" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="modal-video1Label" aria-hidden="true">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&otimes;</button>
                <h3 id="modal-video1Label">Video</h3>
              </div>
              <div class="modal-body">
                        <p>Aenean maximus tristique pretium. Pellentesque egestas arcu et leo commodo, sit amet facilisis nunc facilisis. Ut gravida interdum magna, a facilisis metus tempor vitae.</p>
                        <iframe width="100%" height="315" src="https://www.youtube.com/embed/3TTswKT9J9g" frameborder="0" allowfullscreen></iframe>
              </div>
              <div class="modal-footer">
                <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
              </div>
            </div>

            <div id="modal-video2" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="modal-video2Label" aria-hidden="true">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&otimes;</button>
                <h3 id="modal-video2Label">Video</h3>
              </div>
              <div class="modal-body">
                        <p>Aenean maximus tristique pretium. Pellentesque egestas arcu et leo commodo, sit amet facilisis nunc facilisis. Ut gravida interdum magna, a facilisis metus tempor vitae.</p>
                        <iframe width="100%" height="315" src="https://www.youtube.com/embed/3TTswKT9J9g" frameborder="0" allowfullscreen></iframe>
              </div>
              <div class="modal-footer">
                <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
              </div>
            </div>

            <div id="modal-video3" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="modal-video3Label" aria-hidden="true">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&otimes;</button>
                <h3 id="modal-video3Label">Video</h3>
              </div>
              <div class="modal-body">
                        <p>Aenean maximus tristique pretium. Pellentesque egestas arcu et leo commodo, sit amet facilisis nunc facilisis. Ut gravida interdum magna, a facilisis metus tempor vitae.</p>
                        <iframe width="100%" height="315" src="https://www.youtube.com/embed/3TTswKT9J9g" frameborder="0" allowfullscreen></iframe>
              </div>
              <div class="modal-footer">
                <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
              </div>
            </div>

            <div id="modal-video4" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="modal-video4Label" aria-hidden="true">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&otimes;</button>
                <h3 id="modal-video4Label">Video</h3>
              </div>
              <div class="modal-body">
                        <p>Aenean maximus tristique pretium. Pellentesque egestas arcu et leo commodo, sit amet facilisis nunc facilisis. Ut gravida interdum magna, a facilisis metus tempor vitae.</p>
                        <iframe width="100%" height="315" src="https://www.youtube.com/embed/3TTswKT9J9g" frameborder="0" allowfullscreen></iframe>
              </div>
              <div class="modal-footer">
                <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
              </div>
            </div>

            <div id="modal-video5" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="modal-video5Label" aria-hidden="true">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&otimes;</button>
                <h3 id="modal-video5Label">Video</h3>
              </div>
              <div class="modal-body">
                        <p>Aenean maximus tristique pretium. Pellentesque egestas arcu et leo commodo, sit amet facilisis nunc facilisis. Ut gravida interdum magna, a facilisis metus tempor vitae.</p>
                        <iframe width="100%" height="315" src="https://www.youtube.com/embed/3TTswKT9J9g" frameborder="0" allowfullscreen></iframe>
              </div>
              <div class="modal-footer">
                <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
              </div>
            </div>


</div>