<?php
/**
 * Media Gallery & Product Videos extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   FME
 * @package    Mediaappearance
 * @copyright  Copyright 2010 © free-magentoextensions.com All right reserved
 **/
?>
<?php
    $popupWidth  = Mage::getStoreConfig('mediaappearance/popupsettings/width');
    $popupHeight = Mage::getStoreConfig('mediaappearance/popupsettings/height');
    $autoPlay    = Mage::getStoreConfig('mediaappearance/popupsettings/autoplay');
    $playAgain   = Mage::getStoreConfig('mediaappearance/popupsettings/playagain');

?>
<script type="text/javascript" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS);?>mediaappearance/jquery-1.7.2.min.js"></script>
<script type="text/javascript" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS);?>mediaappearance/jwplayer.js"></script>
<script type="text/javascript" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS);?>mediaappearance/jwplayer.html5.js"></script>
<script type="text/javascript">
    
    jQuery.noConflict();
 jQuery(document).ready(function()
 {
    jQuery(document).ajaxStop(function() {
       jQuery("a.jwVideo").click(function() {
        var myVideo = this.href; // Dont forget about 'this'

        jQuery.fancybox({
            padding : 0,
            content: '<div id="video_container">Loading the player ... </div>',
            afterShow: function(){
                jwplayer("video_container").setup({ 
                    file: myVideo,
                    autostart: true,
                    width  : '<?php echo $popupWidth ?>', // set the width
                    height : '<?php echo $popupHeight ?>',// set the height
                });
            }
        });
        return false;
    });
    jQuery('.fancybox').fancybox({
        openEffect  : 'none',
        closeEffect : 'none',
        width  : '<?php echo $popupWidth ?>', // set the width
        height : '<?php echo $popupHeight ?>',// set the height
        helpers : {
            media : {}
        }
    });

});
});
jQuery.noConflict();
jQuery(document).ready(function() {
    jQuery('.fancybox').fancybox({
        openEffect  : 'none',
        closeEffect : 'none',
        type: "iframe",
        helpers : {
            media : {}
        }
    });

    jQuery("a.jwVideo").click(function() {
        var myVideo = this.href; // Dont forget about 'this'

        jQuery.fancybox({
            padding : 0,
            content: '<div id="video_container">Loading the player ... </div>',
            afterShow: function(){
                jwplayer("video_container").setup({ 
                    file: myVideo,
                    autostart: true,
                    width  : '<?php echo $popupWidth ?>', // set the width
                    height : '<?php echo $popupHeight ?>',// set the height
                    aspectratio: "12:5",
                });
            }
        });
        return false;
    });

    
     
});



</script>

