<?php
/**
 * Media Gallery & Product Videos extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   FME
 * @package    Mediaappearance
 * @copyright  Copyright 2010 © free-magentoextensions.com All right reserved
 **/
?>
<script type="text/javascript">
Shadowbox.init({
    overlayOpacity: 0.8,
	flashVars: {
   		skin: '<?php echo Mage::getBaseUrl('js').'mediaappearance/skin01.zip'?>'
  	}
});
</script>
<?php
	$popupWidth  = Mage::getStoreConfig('mediaappearance/popupsettings/width');
	$popupHeight = Mage::getStoreConfig('mediaappearance/popupsettings/height');
	$autoPlay 	 = Mage::getStoreConfig('mediaappearance/popupsettings/autoplay');
	$playAgain 	 = Mage::getStoreConfig('mediaappearance/popupsettings/playagain');
	$pid = $this->getProduct()->getId(); 

    $media2product = Mage::helper('mediaappearance')->getProductVideos($pid);
    
?>

<?php if (count($media2product)): ?>
<div>
<div class="product-img-box">
<div class="more-views">
    <h2><?php echo $this->__('Product Videos') ?></h2>
    <ul>
                  <?php foreach ($media2product as $_media): ?>
                  <?php
						if($_item["mediatype"] == "1") {
						$data_type = 'data-type="swf"';
						$class= Mage::helper('mediaappearance')->is_image(Mage::getBaseUrl('media').$_item["filename"]);
						$videoURL = Mage::getBaseUrl('media').$_item["filename"];
						$videoRel = 'shadowbox;  height='.$popupHeight.';width='.$popupWidth.';options={flashVars:{skin: '.Mage::getBaseUrl('js').'mediaappearance/skin01.zip,autostart: '.autoPlay.'}}';
						 if($_item["filethumb"] != "") {
							$imgURL = Mage::helper('mediaappearance')->resizeImage($_item["filethumb"]);
						} else {
							$imgURL = Mage::getBaseUrl('media')."mediaappearance/video_icon.jpg";
						} 
						
					} elseif ($_item["mediatype"] == "2") {
						$data_type = 'data-type="iframe"';
						//For Thumb
						$videoURL = $_item["videourl"];
						$videoData = Mage::helper('mediaappearance')->video_info($_item["videourl"]);
						if ($videoData!==false) {
							if($_item["filethumb"] != "") {
									$imgURL = Mage::helper('mediaappearance')->resizeImage($_item["filethumb"]);
								} else {
									$imgURL = Mage::getBaseUrl('media')."mediaappearance/video_icon_full.jpg";
								}
							
						} else {
							if($_item["filethumb"] != "") {
								$imgURL = Mage::getBaseUrl('media').$_item["filethumb"];
							} else {
								$imgURL = Mage::getBaseUrl('media')."mediaappearance/video_icon_full.jpg";
							}
						}
						
						//For Video URL
						if ($videoData!==false) {
							
							$video_type  = $videoData['video_type'];
							$video_id    = $videoData['video_id'];
							if($video_type == "vimeo") {
								$class="fancybox";
								$videoRel = "shadowbox; height=".$popupHeight.";width=".$popupWidth.";options={flashVars:{autostart: ".$autoPlay."}}";
								$videoURL = 'http://player.vimeo.com/video/'.$video_id.'?autoplay=1';
							} elseif($video_type == "youtube") {
								$class="fancybox";
								$videoRel = 'shadowbox;  height='.$popupHeight.';width='.$popupWidth.'; options={flashVars:{autostart: '.$autoPlay.'}}';
								$videoURL = "http://www.youtube.com/embed/".$video_id;
							} 
							
						} else {
							
							$videoURL = $_item["videourl"];
							$videoRel = 'shadowbox; height='.$popupHeight.';width='.$popupWidth.';options={flashVars:{skin: '.Mage::getBaseUrl('js').'mediaappearance/skin01.zip,autostart: '.$autoPlay.'}}';
							
						}
					} else {
						$videoRel = "";
						$videoURL = "#";
						$imgURL = Mage::getBaseUrl('media')."mediaappearance/video_icon_full.jpg";
					}	
					?>
                    <li>
                        <a class="<?php echo $class?>"href="<?php echo $videoURL; ?>" title="<?php echo $_media['title']; ?>" rel="<?php echo $videoRel; ?>" >
                        <img src="<?php echo $imgURL; ?>" width="56" height="56" alt="<?php echo $_media['title']; ?>" /></a>
                    </li>
                  <?php endforeach; ?> 
      </ul>
</div>
</div>
</div>
<?php endif; ?>