<?php
/**
 * 
 * @category   CRM4Ecommerce
 * @package    CRM4Ecommerce_ZohoSynchronization
 * @author     Philip Nguyen <philip@crm4ecommerce.com>
 * @link       http://crm4ecommerce.com
 * @see        CRM4Ecommerce_ZohoSynchronization_Block_Adminhtml_Mapping_Form_New
 */
?>
<div class="entry-edit collapseable">
    <form method="post" action="<?php echo $this->getSaveUrl();?>">
        <input name="c_action" type="hidden" value="<?php echo Mage::registry('c_action');?>" />
        <input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey();?>" />
    <div class="entry-edit-head collapseable">
        <a id="crm4ecommerce_zohosynchronization_lead_subscriber_params-head" class="open" onclick="Fieldset.toggleCollapse('crm4ecommerce_zohosynchronization_lead_subscriber_params'); return false;" href="#">
            <?php echo $this->__('Zoho Lead Settings'); ?>
        </a>
    </div>
    <fieldset id="crm4ecommerce_zohosynchronization_lead_subscriber_params" style="" class="config collapseable">
        <legend><?php echo $this->__('Zoho Lead Settings'); ?></legend>
        <table cellspacing="0" class="form-list" style="width: 100%;">
            <tbody>
                <tr>
                    <td class="label" style="width: 120px;"><label style="width: 120px; padding-right: 0px" for="config[lead_subscriber_duplicate_insert]"><?php echo $this->__('Duplicate Insert') ?></label></td>
                    <td class="value">
                        <select class="input-text" id="config[lead_subscriber_duplicate_insert]" name="config[lead_subscriber_duplicate_insert]" style="width: 97%"><?php
                            $zohoDuplicateChecks = Mage::getModel('zohosynchronization/array_zohoDuplicateCheck')->toOptionArray();
                            foreach ($zohoDuplicateChecks as $key => $value) { ?>
                                <option value="<?php echo $key;?>" <?php echo Mage::getStoreConfig('crm4ecommerce_zohosynchronization/params/lead_subscriber_duplicate_insert') == $key ? 'selected="selected"' : ''; ?>><?php echo $value;?></option>
                            <?php
                            }
                        ?>
                        </select>
                        <p class="note" style="width: 97%;">
                            <span><?php echo $this->__('Zoho Lead has key field is <b>Email</b>.');?></span>
                        </p>
                    </td>
                </tr>
                <tr>
                    <td class="label" style="width: 120px;"><label style="width: 120px; padding-right: 0px" for="config[lead_subscriber_import_all]"><?php echo $this->__('Import all Leads?') ?></label></td>
                    <td class="value">
                        <select class="input-text" id="config[lead_subscriber_import_all]" name="config[lead_subscriber_import_all]" style="width: 97%">
                            <option value="1" <?php echo Mage::getStoreConfig('crm4ecommerce_zohosynchronization/params/lead_subscriber_import_all') == '1' ? 'selected="selected"' : ''; ?>><?php echo $this->__('Yes');?></option>
                            <option value="0" <?php echo Mage::getStoreConfig('crm4ecommerce_zohosynchronization/params/lead_subscriber_import_all') == '0' ? 'selected="selected"' : ''; ?>><?php echo $this->__('No');?></option>
                        ?>
                        </select>
                        <p class="note" style="width: 97%;">
                            <span><?php echo $this->__('Allow importing all Zoho leads that are created from Zoho into Magento Subscribers or not. If this value is Yes, each time we create new or update data of any lead (created in Zoho) on Zoho system, a corresponding Magento subscriber will be created new or updated. With the subscribers that are created in Magento, the bidirectional synchronization is still executed regardless this value is Yes or No.');?></span>
                        </p>
                    </td>
                </tr>
                <?php if (Mage::getStoreConfig('crm4ecommerce_zohosynchronization/params/lead_subscriber_import_all') == '0') { ?>
                <tr>
                    <td class="label" style="width: 120px;"><label style="width: 120px; padding-right: 0px" for="config[lead_subscriber_only_import_has_field]"><?php echo $this->__('Only import Leads have') ?></label></td>
                    <td class="value">
                        <table cellpadding="0" cellspacing="0" border="0" width="97%"><tr>
                                <td style="width: 356px;">
                        <?php 
                            $options = Mage::getStoreConfig('crm4ecommerce_zohosynchronization/mapping_fields/logs/Leads');
                            $group_options = explode('@@', $options);
                        ?>
                        <select class="input-text" id="config[lead_subscriber_only_import_has_field]" name="config[lead_subscriber_only_import_has_field]" style="width: 200px">
                            <?php
                                foreach ($group_options as $group_option) {
                                    $group_option = explode('@', $group_option);
                                    if (count($group_option) > 1) {
                                ?>
                                <optgroup label="<?php echo $group_option[0];?>">
                                <?php
                                    $options = explode(';', $group_option[1]);
                                    foreach ($options as $option) {
                                        $option = explode(',', $option);
                                        if (count($option) == 3) {
                                    ?>
                                    <option <?php echo (Mage::getStoreConfig('crm4ecommerce_zohosynchronization/params/lead_subscriber_only_import_has_field') == $option[0]) ? 'selected="true"' : ''; ?> value="<?php echo $option[0];?>"><?php echo $option[1];?></option>
                                    <?php
                                        }
                                    } ?>
                                </optgroup>
                                <?php }
                                }
                            ?>
                        </select>
                        <select class="input-text" name="config[lead_subscriber_only_import_has_field_condition]" style="width: 150px">
                            <option value="is" <?php echo Mage::getStoreConfig('crm4ecommerce_zohosynchronization/params/lead_subscriber_only_import_has_field_condition') == 'is' ? 'selected="selected"' : ''; ?>><?php echo $this->__('is one of values');?></option>
                            <option value="isnot" <?php echo Mage::getStoreConfig('crm4ecommerce_zohosynchronization/params/lead_subscriber_only_import_has_field_condition') == 'isnot' ? 'selected="selected"' : ''; ?>><?php echo $this->__('is not one of values');?></option>
                        ?>
                        </select>
                                </td>
                        <td>
                            <input type="text" class="input-text" name="config[lead_subscriber_only_import_has_field_condition_values]" style="width: 100%;" value="<?php echo trim(Mage::getStoreConfig('crm4ecommerce_zohosynchronization/params/lead_subscriber_only_import_has_field_condition_values'), ',');?>" />
                        </td></tr></table>
                        <p class="note" style="width: 97%;" style="clear: both;">
                            <span><?php echo $this->__('The values are separated by commas (,). <b>{{empty}}</b> is empty value.');?> <?php echo $this->__('The Zoho Leads that want to be imported into Subscribers must to have email value.');?></span>
                        </p>
                    </td>
                </tr>
                <?php } ?>
                <tr>
                    <td class="label" style="width: 120px;"><label style="width: 120px; padding-right: 0px" for="config[lead_subscriber_default_status]"><?php echo $this->__('Default Status') ?></label></td>
                    <td class="value">
                        <select class="input-text" id="config[lead_subscriber_default_status]" name="config[lead_subscriber_default_status]" style="width: 97%">
                            <option value="<?php echo Mage_Newsletter_Model_Subscriber::STATUS_NOT_ACTIVE;?>" <?php echo Mage::getStoreConfig('crm4ecommerce_zohosynchronization/params/lead_subscriber_default_status') == Mage_Newsletter_Model_Subscriber::STATUS_NOT_ACTIVE ? 'selected="selected"' : ''; ?>><?php echo Mage::helper('newsletter')->__('Not Activated');?></option>
                            <option value="<?php echo Mage_Newsletter_Model_Subscriber::STATUS_SUBSCRIBED;?>" <?php echo Mage::getStoreConfig('crm4ecommerce_zohosynchronization/params/lead_subscriber_default_status') == Mage_Newsletter_Model_Subscriber::STATUS_SUBSCRIBED ? 'selected="selected"' : ''; ?>><?php echo Mage::helper('newsletter')->__('Subscribed');?></option>
                            <option value="<?php echo Mage_Newsletter_Model_Subscriber::STATUS_UNSUBSCRIBED;?>" <?php echo Mage::getStoreConfig('crm4ecommerce_zohosynchronization/params/lead_subscriber_default_status') == Mage_Newsletter_Model_Subscriber::STATUS_UNSUBSCRIBED ? 'selected="selected"' : ''; ?>><?php echo Mage::helper('newsletter')->__('Unsubscribed');?></option>
                            <option value="<?php echo Mage_Newsletter_Model_Subscriber::STATUS_UNCONFIRMED;?>" <?php echo Mage::getStoreConfig('crm4ecommerce_zohosynchronization/params/lead_subscriber_default_status') == Mage_Newsletter_Model_Subscriber::STATUS_UNCONFIRMED ? 'selected="selected"' : ''; ?>><?php echo Mage::helper('newsletter')->__('Unconfirmed');?></option>
                        ?>
                        </select>
                        <p class="note" style="width: 97%;">
                            <span><?php echo $this->__("Default status of created new subscriber when zoho admin create new a lead but didn't input subscriber status.");?></span>
                        </p>
                    </td>
                </tr>
                <tr>
                    <td class="label" colspan="2"><b><?php echo $this->__("When subscribers are deleted") ?>:</b></td>
                </tr>
                <tr>
                    <td class="label" style="width: 120px;"><label style="width: 120px; padding-right: 0px" for="config[lead_subscriber_allow_delete]"><?php echo $this->__('Allow Delete Lead in ZohoCRM') ?></label></td>
                    <td class="value">
                        <select class="input-text" id="config[lead_subscriber_allow_delete]" name="config[lead_subscriber_allow_delete]" style="width: 97%">
                            <option value="1" <?php echo Mage::getStoreConfig('crm4ecommerce_zohosynchronization/params/lead_subscriber_allow_delete') == '1' ? 'selected="selected"' : ''; ?>><?php echo $this->__('Yes');?></option>
                            <option value="0" <?php echo Mage::getStoreConfig('crm4ecommerce_zohosynchronization/params/lead_subscriber_allow_delete') == '0' ? 'selected="selected"' : ''; ?>><?php echo $this->__('No');?></option>
                        ?>
                        </select>
                        <p class="note" style="width: 97%;">
                            <span><?php echo $this->__('Allow delete corresponding lead in ZohoCRM when subscriber is deleted or not.');?></span>
                        </p>
                    </td>
                </tr>
                <?php if (Mage::getStoreConfig('crm4ecommerce_zohosynchronization/params/lead_subscriber_allow_delete') == '0') { ?>
                <tr>
                    <td class="label" style="width: 120px;"><label style="width: 120px; padding-right: 0px" for="config[lead_subscriber_update_field]"><?php echo $this->__('Update field') ?></label></td>
                    <td class="value">
                        <table cellpadding="0" cellspacing="0" border="0" width="97%"><tr>
                                <td style="width: 203px;">
                        <?php 
                            $options = Mage::getStoreConfig('crm4ecommerce_zohosynchronization/mapping_fields/logs/Leads');
                            $group_options = explode('@@', $options);
                        ?>
                        <select class="input-text" id="config[lead_subscriber_update_field]" name="config[lead_subscriber_update_field]" style="width: 200px">
                            <option value=""><?php echo $this->__('None'); ?></option>
                            <?php
                                foreach ($group_options as $group_option) {
                                    $group_option = explode('@', $group_option);
                                    if (count($group_option) > 1) {
                                ?>
                                <optgroup label="<?php echo $group_option[0];?>">
                                <?php
                                    $options = explode(';', $group_option[1]);
                                    foreach ($options as $option) {
                                        $option = explode(',', $option);
                                        if (count($option) == 3) {
                                    ?>
                                    <option <?php echo (Mage::getStoreConfig('crm4ecommerce_zohosynchronization/params/lead_subscriber_update_field') == $option[0]) ? 'selected="true"' : ''; ?> value="<?php echo $option[0];?>"><?php echo $option[1];?></option>
                                    <?php
                                        }
                                    } ?>
                                </optgroup>
                                <?php }
                                }
                            ?>
                        </select>
                                </td>
                                <td style="width: 18px; text-align: center;"><?php echo $this->__('is');?></td>
                        <td>
                            <input type="text" class="input-text" name="config[lead_subscriber_update_field_value]" style="width: 100%;" value="<?php echo Mage::getStoreConfig('crm4ecommerce_zohosynchronization/params/lead_subscriber_update_field_value');?>" />
                        </td></tr></table>
                    </td>
                </tr>
                <?php } ?>
            </tbody>
        </table>
        <div style="text-align: right; margin-top: 5px; padding-top: 10px; border-top: 2px solid #CCCCCC;">        
            <table style="width: 100%;"><tr><td>                    
                <button name="submit" value="save" class="scalable save" style="" type="submit">
                    <span><span><span><?php echo $this->__('Save');?></span></span></span>
                </button></td></tr>
            </table>
        </div>
    </fieldset>
    <script type="text/javascript">
        Fieldset.applyCollapse('crm4ecommerce_zohosynchronization_lead_subscriber_params');
    </script>
    </form>
</div>