<div class="container">
        <div class="seen-box">
            <h2>As Seen On</h2>
            <img src="<?php echo $this->getSkinUrl(); ?>images/misc/as-seen.png"  class="logos" alt="As Seen On">
            <div class="clear"></div>
        </div>
</div>

<div class="container">
    <div class="radio-int">
        <script src="<?php echo $this->getSkinUrl(); ?>js/audio.min.js"></script>
        <script>
          audiojs.events.ready(function() {
            var as = audiojs.createAll();
          });
        </script>
        <style>
        .audiojs {   margin:0 auto;  }

        </style>
        <h2>Dr. Dave Janda's Radio Interview with NuManna's Founder and Executive Director, Danial Brigman...</h2>
        <p>Listen now, as they discuss why NuManna is the #1 company that you and your family should turn to when it comes to food preparedness quality and taste.</p>
        <audio src="<?php echo $this->getSkinUrl(); ?>mp3/DanielBrigman092516.mp3" preload="auto" /></audio>
    </div>
</div>

<div class="container">
<?php
$block = Mage::getModel('widget/widget_instance')->load(4);
$blockpars = $block->getWidgetParameters();
?>


<div class="testimonials">

<script type="text/javascript">

$(document).ready(function () {
    //rotation speed and timer
    var speed = 5000;

    var run = setInterval(rotate, speed);
    var slides = $('.slide');
    var container = $('#slides ul');
    var elm = container.find(':first-child').prop("tagName");
    var item_width = container.width();
    var previous = 'prev'; //id of previous button
    var next = 'next'; //id of next button
    slides.width(item_width); //set the slides to the correct pixel width
    container.parent().width(item_width);
    container.width(slides.length * item_width); //set the slides container to the correct total width
    container.find(elm + ':first').before(container.find(elm + ':last'));
    resetSlides();


    //if user clicked on prev button

    $('#buttons a').click(function (e) {
        //slide the item

        if (container.is(':animated')) {
            return false;
        }
        if (e.target.id == previous) {
            container.stop().animate({
                'left': 0
            }, 1500, function () {
                container.find(elm + ':first').before(container.find(elm + ':last'));
                resetSlides();
            });
        }

        if (e.target.id == next) {
            container.stop().animate({
                'left': item_width * -2
            }, 1500, function () {
                container.find(elm + ':last').after(container.find(elm + ':first'));
                resetSlides();
            });
        }

        //cancel the link behavior
        return false;

    });

    //if mouse hover, pause the auto rotation, otherwise rotate it
    container.parent().mouseenter(function () {
        clearInterval(run);
    }).mouseleave(function () {
        run = setInterval(rotate, speed);
    });


    function resetSlides() {
        //and adjust the container so current is in the frame
        container.css({
            'left': -1 * item_width
        });
    }

});
//a simple function to click next link
//a timer will call this function, and the rotation will begin

function rotate() {
    $('#next').click();
}


</script>


<style>

#carousel_testimonials_numanna {
position: relative;
width:60%;
margin:0 auto;
}

#slides {
overflow: hidden;
position: relative;
width: 100%;
height: 250px;
}

#slides ul {
list-style: none;
width:100%;
height:250px;
margin: 0;
padding: 0;
position: relative;
}

 #slides li {
width:100%;
height:250px;
float:left;
text-align: center;
position: relative;
font-family:lato, sans-serif;
}
/* Styling for prev and next buttons */
.btn-bar{
width:60%;
margin:0 auto;
display:block;
position:relative;
top:40px;
}

 #buttons {
padding:0 0 5px 0;
float:right;
}

#buttons a {
text-align:center;
display:block;
font-size:50px;
float:left;
outline:0;
margin:0 60px;
color:#b14943;
text-decoration:none;
display:block;
padding:9px;
width:35px;
}

a#prev:hover, a#next:hover {
color:#FFF;
text-shadow:.5px 0px #b14943;
}

.quote-phrase, .quote-author {
font-family:sans-serif;
font-weight:300;
display: table-cell;
vertical-align: middle;
padding: 5px 20px;
font-family:'Lato', Calibri, Arial, sans-serif;
}

.quote-phrase {
height: 200px;
font-size:24px;
color:#FFF;
font-style:italic;
text-shadow:.5px 0px #b14943;
}

.quote-marks {
font-size:30px;
padding:0 3px 3px;
position:inherit;
}

.quote-author {
font-style:normal;
font-size:20px;
color:#b14943;
font-weight:400;
height: 30px;
}

.quoteContainer, .authorContainer {
display: table;
width: 100%;
}
</style>


                <h3>Client Testimonials</h3>

<div id="carousel_testimonials_numanna">
  <div class="btn-bar">
    <div id="buttons"><a id="prev" href="#"><</a><a id="next" href="#">></a> </div></div>
    <div id="slides">
        <ul>
      <li class="slide">
      <div class="quoteContainer">
      <p class="quote-phrase"><span class="quote-marks">"</span> "I have tried several different brands of storable foods and NuManna has been the best. The food looks like actual food. Although it was difficult to pick a favorite as all are delicious...makes my mouth salivate just typing about it! Thank you NuManna for making incredible food!""</p>
      </div>

      <div class="authorContainer">
      <p class="quote-author"><strong>— Jayme, Texas</strong></p>
      </div>
      </li>
      <li class="slide">
      <div class="quoteContainer">
      <p class="quote-phrase"><span class="quote-marks">"</span> "I really appreciate the high quality non GMO products you carry and I especially like the packaging. Very professional to say the least. I really like spicy chili and your habanero chili is the best, in my opinion. Thanks for the custom order.<br />
      You make it so that having an emergency supply doesn't have to feel like I'm "roughing it" so thanks for that! I've had to reorder since I sometimes enjoy Numanna even in the good times...""</p>
      </div>

      <div class="authorContainer">
      <p class="quote-author"><strong>— James, San Antonio, Lone Star State</strong></p>
      </div>
      </li>
      <li class="slide">
      <div class="quoteContainer">
      <p class="quote-phrase"><span class="quote-marks">"</span> "I have tried all kinds of food storage...this is the best tasting food of any I've tried.""</p>
      </div>

      <div class="authorContainer">
      <p class="quote-author"><strong>— Gayle, Springville, UT</strong></p>
      </div>
      </li>
      <li class="slide">
      <div class="quoteContainer">
      <p class="quote-phrase"><span class="quote-marks">"</span> "I was very surprised after eating NuManna. First it tastes great. Second, most storable foods give me a bit of an uneasy feeling after eating them. I have food sensitivities. I did not experience any of the typical stomach problems for eating a dehydrated food product. NuManna is the best I have ever had.""</p>
      </div>

      <div class="authorContainer">
      <p class="quote-author"><strong>— Tim C., California</strong></p>
      </div>
      </li>
      <li class="slide">
      <div class="quoteContainer">
      <p class="quote-phrase"><span class="quote-marks">"</span> "This stuff is awesome. My wife has been away for a while so I ate NuManna while she was gone. It was simple and everything I had was really good. I wish NuManna was around when I bought a bunch of bulk food in the past from the Mormons. I don’t want to have all these ingredients and put them together. NuManna was simple and great tasting. I gave away all my other bulk food.""</p>
      </div>

      <div class="authorContainer">
      <p class="quote-author"><strong>— Reagan B., Mexico</strong></p>
      </div>
      </li>
      <li class="slide">
      <div class="quoteContainer">
      <p class="quote-phrase"><span class="quote-marks">"</span> "I host a national radio show and I have been around this industry for a long time and seen just about everything that is out there. I have never tasted storable food as good as NuManna and I’ll put my name on that. My wife and I took some of the Pasta Primavera to a church function and people couldn’t believe this was storable food. It was so creamy. The Habanero chili could win a cook-off it’s that good. NuManna is the brand we recommend because it is the best we have ever tasted and the People behind the company are first rate.""</p>
      </div>

      <div class="authorContainer">
      <p class="quote-author"><strong>— Pastor Butch, West Virginia</strong></p>
      </div>
      </li>
      <li class="slide">
      <div class="quoteContainer">
      <p class="quote-phrase"><span class="quote-marks">"</span> "I’ve been in search of a storable food product that would help you and your family. I’ve tested a number of products and I’ve researched a number of companies and I actually have finally come up with a company and a product line that I believe that you need to utilize to help protect yourself and your family. The name of the company is NuManna.""</p>
      </div>

      <div class="authorContainer">
      <p class="quote-author"><strong>— Dr. Dave Janda</strong></p>
      </div>
      </li>
      <li class="slide">
      <div class="quoteContainer">
      <p class="quote-phrase"><span class="quote-marks">"</span> "I received the sampler pack last week and was pleasantly surprised at how good the food is. The portion size was perfect for both my husband and I to try. His comment was, ‘this is actually really good tasting’. Also, the fact that this is non-gmo food is a major plus! We will definitely be ordering from you again. Thank you so much for a great product, and offering the sample packs to try.""</p>
      </div>

      <div class="authorContainer">
      <p class="quote-author"><strong>— Sherrie S.</strong></p>
      </div>
      </li>
      <li class="slide">
      <div class="quoteContainer">
      <p class="quote-phrase"><span class="quote-marks">"</span> "I have done a lot of research over the past 5 to 6 months. I keep coming back to your brand and business model time after time when comparing to other survival foods. I look forward to receiving your products soon. Cheers.""</p>
      </div>

      <div class="authorContainer">
      <p class="quote-author"><strong>— David W.</strong></p>
      </div>
      </li>
      <li class="slide">
      <div class="quoteContainer">
      <p class="quote-phrase"><span class="quote-marks">"</span> "I believe that this is one of the best investments that you can make for your family to be prepared for what ever the future might hold. Remember… you can’t eat gold, but you can eat NuManna Food Storage during a time of crisis.""</p>
      </div>

      <div class="authorContainer">
      <p class="quote-author"><strong>— Joyce Riley host of The Power Hour</strong></p>
      </div>
      </li>
      <li class="slide">
      <div class="quoteContainer">
      <p class="quote-phrase"><span class="quote-marks">"</span> "There are excesses of organizations stuffing their pails with sugary beverage blends and abandons. NuManna has genuine nourishment that manages you in a crisis circumstance... GMO Free, simple to alter dinners and natural superfoods. Simple to transport and 25 or more year time span of usability. Everybody needs to consider their independence. NuManna has turned into the foundation of my long haul sustenance stockpiling. NuManna is nourishment stockpiling you’ll adore to eat.""</p>
      </div>

      <div class="authorContainer">
      <p class="quote-author"><strong>— Steve Quayle</strong></p>
      </div>
      </li>
</ul>
    </div>
</div>


        <!-- <div class="testimonials">
                <h3><?php echo $blockpars['title'] ?></h3>
                <p class="testimonial"><?php echo $blockpars['text'] ?></p>
                <p class="author"><strong>&mdash; <?php echo $blockpars['author'] ?></strong>  &nbsp;&nbsp;&nbsp;&nbsp;<a href="<?php echo $blockpars['link_href'] ?>"><?php echo $blockpars['link_title'] ?></a></p>
        </div> -->


<!--        <div class="seen-box">
            <h2>As Seen On</h2>
            <img src="<?php echo $this->getSkinUrl(); ?>images/misc/as-seen.png"  class="logos" alt="As Seen On">
            <div class="clear"></div>
        </div>-->

</div>

<div class="carousel home-carousel">
    <div class="wide-container">
        <div class="container center">
             <h2>Featured Products</h2>
              <div class="carousel-holder">


                  <script src="<?php echo $this->getSkinUrl(); ?>js/owl.carousel2.js" type="text/javascript"></script>
                  <script src="<?php echo $this->getSkinUrl(); ?>js/owl.carousel2.navigation.js" type="text/javascript"></script>
                  <!-- Owl Carousel -->
                  <div class="owl-carousel-wrapper">
                  <div id="owl-carousel1" class="owl-carousel">
                      <?php
                      $cat_id = "24";
                      $_productCollection = Mage::getResourceModel('catalog/product_collection')
                      ->addAttributeToSelect(array('name', 'price', 'small_image', 'short_description'), 'inner')
                      ->addCategoryFilter(Mage::getModel('catalog/category')->load($cat_id));

                      if(!$_productCollection->count()):
                          echo $this->__('There are no products matching the selection.');
                      else: ?>


                              <?php $i=0; foreach ($_productCollection as $_product): ?>
                                          <div class="item featured-product">
                                          <div class="inner">
                                                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image')) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(300,300); ?>" alt="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image')) ?>" title="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image')) ?>" />
                                                </a>
                                                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image')) ?>" class="name"><?php echo $_product->getName(); ?></a>
                                                <p class="price"><strong><?php echo Mage::app()->getLocale()->currency(Mage::app()->getStore()->getCurrentCurrencyCode())->getSymbol(); ?><?php echo $this->htmlEscape(sprintf("%0.2f",$_product->getFinalPrice())) ?></strong></p>
                                          </div>
                                          </div>
                              <?php endforeach ?>

                      <?php endif; ?>
                  </div>
                  </div>
                  <script type="text/javascript">
                      jQuery(document).ready(function() {
                        jQuery('#owl-carousel1').owlCarousel({
                            loop:true,
                            dots:false,
                            center:false,
                            navigation:true,
                            margin:20,
                            responsive:{
                                0:{
                                    items:1,
                                    nav:true
                                },
                                600:{
                                    items:2,
                                    nav:true
                                },
                                800:{
                                    items:3,
                                    nav:true
                                },
                                900:{
                                    items:4,
                                    nav:true
                                },
                                1000:{
                                    items:4,
                                    nav:true,
                                }
                            }
                        });

                      });
                  </script>


              </div>
        </div>
    </div>
</div>

<div class="container">
    <div class="row"><div class="span12 col"><a href="<?php echo $this->getUrl(); ?>sample-pack/"><img src="<?php echo $this->getSkinUrl(); ?>images/misc/hpsample.jpg"  alt="Sample Pack"></a></div></div>
</div>

<div class="container">
        <div class="info-boxes">
                <div class="row">
                    <div class="span4 col">
<?php
$block = Mage::getModel('widget/widget_instance')->load(1);
$blockpars = $block->getWidgetParameters();
?>
                        <img src="<?php echo  Mage::getBaseUrl('media') . $blockpars['image'] ?>" alt="">
                        <h2><?php echo $blockpars['title'] ?></h2>
                        <p><?php echo $blockpars['content'] ?></p>
                        <a href="<?php echo $blockpars['link_href'] ?>" class="text-link"><?php echo $blockpars['link_title'] ?></a>
                    </div>
<?php
$block = Mage::getModel('widget/widget_instance')->load(2);
$blockpars = $block->getWidgetParameters();
?>
                    <div class="span4 col">
                        <img src="<?php echo  Mage::getBaseUrl('media') . $blockpars['image'] ?>" alt="">
                        <h2><?php echo $blockpars['title'] ?></h2>
                        <p><?php echo $blockpars['content'] ?></p>
                        <a href="<?php echo $blockpars['link_href'] ?>" class="text-link"><?php echo $blockpars['link_title'] ?></a>
                    </div>
<?php
$block = Mage::getModel('widget/widget_instance')->load(3);
$blockpars = $block->getWidgetParameters();
?>
                    <div class="span4 col">
                        <img src="<?php echo  Mage::getBaseUrl('media') . $blockpars['image'] ?>" alt="">
                        <h2><?php echo $blockpars['title'] ?></h2>
                        <p><?php echo $blockpars['content'] ?></p>
                        <a href="<?php echo $blockpars['link_href'] ?>" class="text-link"><?php echo $blockpars['link_title'] ?></a>
                    </div>
                </div>
        </div>

        <div class="guarantees">
                <h3>Our Guarantees</h3>

                <ul>
                    <li>
                        <img src="<?php echo $this->getSkinUrl(); ?>images/misc/seal-25plus.png" width="183" height="183" alt="">
                        <strong>25+ Year Shelf Life</strong>
                    </li>
                    <li>
                        <img src="<?php echo $this->getSkinUrl(); ?>images/misc/seal-msg.png" width="183" height="183" alt="">
                        <strong>MSG FREE</strong>
                    </li>
                    <li>
                        <img src="<?php echo $this->getSkinUrl(); ?>images/misc/seal-gmo.png" width="183" height="183" alt="">
                        <strong>GMO FREE</strong>
                    </li>
                    <li>
                        <img src="<?php echo $this->getSkinUrl(); ?>images/misc/seal-nopv.png" width="183" height="183" alt="">
                        <strong>No Preservatives</strong>
                    </li>
                    <li>
                        <img src="<?php echo $this->getSkinUrl(); ?>images/misc/seal-america.png" width="183" height="183" alt="">
                        <strong>Made in America</strong>
                    </li>
                </ul>
        </div>


</div>
