<div class="container">
        <div class="seen-box">
            <h2>As Seen On</h2>
            <img src="<?php echo $this->getSkinUrl(); ?>images/misc/as-seen.png"  class="logos" alt="As Seen On">
            <div class="clear"></div>
        </div>
</div>

<div class="container">
    <div class="radio-int">
        <script src="<?php echo $this->getSkinUrl(); ?>js/audio.min.js"></script>
        <script>
          audiojs.events.ready(function() {
            var as = audiojs.createAll();
          });
        </script>
        <style>
        .audiojs {   margin:0 auto;  }

        </style>
        <h2>Dr. Dave Janda's Radio Interview with NuManna's Founder and Executive Director, Danial Brigman...</h2>
        <p>Listen now, as they discuss why NuManna is the #1 company that you and your family should turn to when it comes to food preparedness quality and taste.</p>
        <audio src="<?php echo $this->getSkinUrl(); ?>mp3/DanielBrigman092516.mp3" preload="auto" /></audio>
    </div>
</div>

<div class="container">
<?php
$block = Mage::getModel('widget/widget_instance')->load(4);
$blockpars = $block->getWidgetParameters();
?>
        <div class="testimonials">
                <h3><?php echo $blockpars['title'] ?></h3>
                <p class="testimonial"><?php echo $blockpars['text'] ?></p>
                <p class="author"><strong>&mdash; <?php echo $blockpars['author'] ?></strong>  &nbsp;&nbsp;&nbsp;&nbsp;<a href="<?php echo $blockpars['link_href'] ?>"><?php echo $blockpars['link_title'] ?></a></p>
        </div>


<!--        <div class="seen-box">
            <h2>As Seen On</h2>
            <img src="<?php echo $this->getSkinUrl(); ?>images/misc/as-seen.png"  class="logos" alt="As Seen On">
            <div class="clear"></div>
        </div>-->

</div>

<div class="carousel home-carousel">
    <div class="wide-container">
        <div class="container center">
             <h2>Featured Products</h2>
              <div class="carousel-holder">


                  <script src="<?php echo $this->getSkinUrl(); ?>js/owl.carousel2.js" type="text/javascript"></script>
                  <script src="<?php echo $this->getSkinUrl(); ?>js/owl.carousel2.navigation.js" type="text/javascript"></script>
                  <!-- Owl Carousel -->
                  <div class="owl-carousel-wrapper">
                  <div id="owl-carousel1" class="owl-carousel">
                      <?php
                      $cat_id = "24";
                      $_productCollection = Mage::getResourceModel('catalog/product_collection')
                      ->addAttributeToSelect(array('name', 'price', 'small_image', 'short_description'), 'inner')
                      ->addCategoryFilter(Mage::getModel('catalog/category')->load($cat_id));

                      if(!$_productCollection->count()):
                          echo $this->__('There are no products matching the selection.');
                      else: ?>


                              <?php $i=0; foreach ($_productCollection as $_product): ?>
                                          <div class="item featured-product">
                                          <div class="inner">
                                                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image')) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(300,300); ?>" alt="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image')) ?>" title="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image')) ?>" />
                                                </a>
                                                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image')) ?>" class="name"><?php echo $_product->getName(); ?></a>
                                                <p class="price"><strong><?php echo Mage::app()->getLocale()->currency(Mage::app()->getStore()->getCurrentCurrencyCode())->getSymbol(); ?><?php echo $this->htmlEscape(sprintf("%0.2f",$_product->getFinalPrice())) ?></strong></p>
                                          </div>
                                          </div>
                              <?php endforeach ?>

                      <?php endif; ?>
                  </div>
                  </div>
                  <script type="text/javascript">
                      jQuery(document).ready(function() {
                        jQuery('#owl-carousel1').owlCarousel({
                            loop:true,
                            dots:false,
                            center:false,
                            navigation:true,
                            margin:20,
                            responsive:{
                                0:{
                                    items:1,
                                    nav:true
                                },
                                600:{
                                    items:2,
                                    nav:true
                                },
                                800:{
                                    items:3,
                                    nav:true
                                },
                                900:{
                                    items:4,
                                    nav:true
                                },
                                1000:{
                                    items:4,
                                    nav:true,
                                }
                            }
                        });

                      });
                  </script>


              </div>
        </div>
    </div>
</div>

<div class="container">
    <div class="row"><div class="span12 col"><a href="<?php echo $this->getUrl(); ?>sample-pack/"><img src="<?php echo $this->getSkinUrl(); ?>images/misc/hpsample.jpg"  alt="Sample Pack"></a></div></div>
</div>

<div class="container">
        <div class="info-boxes">
                <div class="row">
                    <div class="span4 col">
<?php
$block = Mage::getModel('widget/widget_instance')->load(1);
$blockpars = $block->getWidgetParameters();
?>
                        <img src="<?php echo  Mage::getBaseUrl('media') . $blockpars['image'] ?>" alt="">
                        <h2><?php echo $blockpars['title'] ?></h2>
                        <p><?php echo $blockpars['content'] ?></p>
                        <a href="<?php echo $blockpars['link_href'] ?>" class="text-link"><?php echo $blockpars['link_title'] ?></a>
                    </div>
<?php
$block = Mage::getModel('widget/widget_instance')->load(2);
$blockpars = $block->getWidgetParameters();
?>
                    <div class="span4 col">
                        <img src="<?php echo  Mage::getBaseUrl('media') . $blockpars['image'] ?>" alt="">
                        <h2><?php echo $blockpars['title'] ?></h2>
                        <p><?php echo $blockpars['content'] ?></p>
                        <a href="<?php echo $blockpars['link_href'] ?>" class="text-link"><?php echo $blockpars['link_title'] ?></a>
                    </div>
<?php
$block = Mage::getModel('widget/widget_instance')->load(3);
$blockpars = $block->getWidgetParameters();
?>
                    <div class="span4 col">
                        <img src="<?php echo  Mage::getBaseUrl('media') . $blockpars['image'] ?>" alt="">
                        <h2><?php echo $blockpars['title'] ?></h2>
                        <p><?php echo $blockpars['content'] ?></p>
                        <a href="<?php echo $blockpars['link_href'] ?>" class="text-link"><?php echo $blockpars['link_title'] ?></a>
                    </div>
                </div>
        </div>

        <div class="guarantees">
                <h3>Our Guarantees</h3>

                <ul>
                    <li>
                        <img src="<?php echo $this->getSkinUrl(); ?>images/misc/seal-25plus.png" width="183" height="183" alt="">
                        <strong>25+ Year Shelf Life</strong>
                    </li>
                    <li>
                        <img src="<?php echo $this->getSkinUrl(); ?>images/misc/seal-msg.png" width="183" height="183" alt="">
                        <strong>MSG FREE</strong>
                    </li>
                    <li>
                        <img src="<?php echo $this->getSkinUrl(); ?>images/misc/seal-gmo.png" width="183" height="183" alt="">
                        <strong>GMO FREE</strong>
                    </li>
                    <li>
                        <img src="<?php echo $this->getSkinUrl(); ?>images/misc/seal-nopv.png" width="183" height="183" alt="">
                        <strong>No Preservatives</strong>
                    </li>
                    <li>
                        <img src="<?php echo $this->getSkinUrl(); ?>images/misc/seal-america.png" width="183" height="183" alt="">
                        <strong>Made in America</strong>
                    </li>
                </ul>
        </div>


</div>
