<?php

/**
 * 
 * @category   CRM4Ecommerce
 * @package    CRM4Ecommerce_ZohoSynchronization
 * @author     Philip Nguyen <philip@crm4ecommerce.com>
 * @link       http://crm4ecommerce.com
 * @see        CRM4Ecommerce_ZohoSynchronization_Block_Adminhtml_Log_View_Tab_Form
 */
?>
<div class="entry-edit">
    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('Log Information') ?></h4>
    </div>
    <div class="fieldset">
        <table cellspacing="0" class="form-list">
            <tbody>
                <tr>
                    <td class="label"><label for="title"><?php echo $this->__('Data Type') ?></label></td>
                    <td class="value" style="font-weight: bold; white-space: nowrap;">
                        <a style="text-decoration: none;"><?php
                            echo Mage::getModel('zohosynchronization/array_logDataType')->getDataType(Mage::registry('log_data')->getTypeData())
                        ?></a>
                    </td>
                </tr>
                <tr>
                    <td class="label"><label for="title"><?php echo $this->__('Log Mode') ?></label></td>
                    <td class="value" style="font-weight: bold; white-space: nowrap;">
                        <a style="text-decoration: none;"><?php
                            echo Mage::getModel('zohosynchronization/array_logMode')->getDataType(Mage::registry('log_data')->getMode())
                        ?></a>
                    </td>
                </tr>
                <tr>
                    <td class="label"><label for="title"><?php echo $this->__('Log Action') ?></label></td>
                    <td class="value" style="font-weight: bold; white-space: nowrap;">
                        <a style="text-decoration: none;"><?php
                            echo Mage::getModel('zohosynchronization/array_logAction')->getDataType(Mage::registry('log_data')->getAction())
                        ?></a>
                    </td>
                </tr>
                <?php if ((int) Mage::registry('log_data')->getQueueId() > 0) { ?>
                <tr>
                    <td class="label"><label for="title"><?php echo $this->__('Queue Item') ?></label></td>
                    <td class="value" style="font-weight: bold; white-space: nowrap;">
                        <a href="<?php $this->getUrl('zohosynchronization/adminhtml_queue/edit', array('id' => Mage::registry('log_data')->getQueueId()));?>"><?php
                            echo Mage::registry('log_data')->getQueueId()
                        ?></a>
                    </td>
                </tr>
                <?php } ?>
                <tr>
                    <td class="label"><label for="title"><?php echo $this->__('From Store') ?></label></td>
                    <td class="value" style="font-weight: bold; white-space: nowrap;">
                        <?php
                            $website = Mage::registry('log_data')->getWebsite();
                            $store_group = Mage::registry('log_data')->getStoreGroup();
                            $store = Mage::registry('log_data')->getStore();
                        ?>
                        <b><?php if (!is_null($website)) {
                                echo $website->getName(); ?> | <?php echo $store_group->getName(); ?> | <?php echo $store->getName();
                            } else {
                                echo $this->__('Admin');
                            } ?></b>
                    </td>
                </tr>
                <tr>
                    <td class="label"><label for="title"><?php echo $this->__('Status') ?></label></td>
                    <td class="value" style="font-weight: bold;">
                        <?php echo Mage::registry('log_data')->getStatus() ?
                                '<span style="border: 2px solid #006699; font-size: 10px; font-weight: bold; background-color: #3366CC; padding: 3px 5px 3px 5px; color: #FFFFFF; text-transform: uppercase;">' . Mage::getModel('zohosynchronization/array_logAction')->getDataTypePast(Mage::registry('log_data')->getAction()) . ' ' . $this->__('Successfully') . '</span>' :
                                '<span style="border: 2px solid #990000; font-size: 10px; font-weight: bold; background-color: #CC3300; padding: 3px 5px 3px 5px; color: #FFFFFF; text-transform: uppercase;">' . Mage::getModel('zohosynchronization/array_logAction')->getDataTypePast(Mage::registry('log_data')->getAction()) . ' ' . $this->__('Unsuccessfully') . '</span>' ?>
                    </td>
                </tr>
                <?php if (Mage::registry('log_data')->getFromId() != '' || Mage::registry('log_data')->getToId() != '') { ?>
                    <tr>
                        <td class="label"><label for="title"><?php echo $this->__('Domain Affected Ids') ?></label></td>
                        <td class="value" style="white-space: nowrap;">
                            <?php if (Mage::registry('log_data')->getFromId() != Mage::registry('log_data')->getToId()) { ?>
                                <?php echo $this->__('From Id') ?>: <b><?php echo Mage::registry('log_data')->getFromId() ?></b>,
                                <?php echo $this->__('To Id') ?>: <b><?php echo Mage::registry('log_data')->getToId() ?></b>
                            <?php } else { ?>
                                <?php echo $this->__('Affected Id') ?>: <b><?php echo Mage::registry('log_data')->getFromId() ?></b>
                            <?php } ?>
                        </td>
                    </tr>
                <?php } ?>
                <?php if ((Mage::registry('log_data')->getFromId() == '' && Mage::registry('log_data')->getToId() == '') || (Mage::registry('log_data')->getFromId() != Mage::registry('log_data')->getToId())) { ?>
                    <tr>
                        <td class="label"><label for="title"><?php echo $this->__('Number Success') ?></label></td>
                        <td class="value" style="font-weight: bold; white-space: nowrap;">
                            <?php
                                echo Mage::registry('log_data')->getNumberSuccess() . "/" . ((int)Mage::registry('log_data')->getNumberSuccess() + (int)Mage::registry('log_data')->getNumberFailure())
                            ?>
                        </td>
                    </tr>
                    <?php if (Mage::registry('log_data')->getSuccessIds() != '') { ?>
                        <tr>
                            <td class="label"><label for="title"><?php echo $this->__('Success Ids') ?></label></td>
                            <td class="value" style="font-weight: bold; white-space: nowrap;">
                                <?php
                                    echo Mage::registry('log_data')->getSuccessIds()
                                ?>
                            </td>
                        </tr>
                    <?php } ?>
                    <?php if (Mage::registry('log_data')->getFailureIds() != '') { ?>
                        <tr>
                            <td class="label"><label for="title"><?php echo $this->__('Failure Ids') ?></label></td>
                            <td class="value" style="font-weight: bold; white-space: nowrap;">
                                <?php
                                    echo Mage::registry('log_data')->getFailureIds()
                                ?>
                            </td>
                        </tr>
                    <?php } ?>
                <?php } ?>
                <tr>
                    <td class="label"><label for="title"><?php echo $this->__('Synchronization Started Time') ?></label></td>
                    <td class="value">
                        <?php
                            $start_time = Mage::registry('log_data')->getStartTime();
                            echo Mage::app()->getLocale()->date($start_time, Varien_Date::DATETIME_INTERNAL_FORMAT)->toString();
                        ?>
                    </td>
                </tr>
                <tr>
                    <td class="label"><label for="title"><?php echo $this->__('Synchronization Logged Time') ?></label></td>
                    <td class="value">
                        <?php
                            $log_time = Mage::registry('log_data')->getLogTime();
                            echo Mage::app()->getLocale()->date($log_time, Varien_Date::DATETIME_INTERNAL_FORMAT)->toString();
                        ?>
                    </td>
                </tr>
                <tr>
                    <td class="label"><label for="title"><?php echo $this->__('Synchronization In Time') ?></label></td>
                    <td class="value">
                        <?php
                            echo '<b>' . Mage::registry('log_data')->getLogInTime() . '</b> ' . $this->__('second(s)');
                        ?>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
</div>