<?php if ($_products = $this->getRecentlyComparedProducts()): ?>
<div class="block block-list block-compared">
    <div class="block-title">
        <strong><span><?php echo $this->__('Recently Compared Products') ?></span></strong>
    </div>
    <div class="block-content">
        <?php foreach ($_products as $_item): ?>
            <div class="item">
                <p class="product-name"><a href="<?php echo $this->getProductUrl($_item) ?>"><?php echo $this->helper('catalog/output')->productAttribute($_item, $_item->getName() , 'name') ?></a></p>
            </div>
        <?php endforeach; ?>
    </div>
</div>
<?php endif; ?>
