<meta http-equiv="X-UA-Compatible" content="IE=9; IE=8; IE=7; IE=EDGE" />
<meta http-equiv="content-type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="author" content="TransformAgency.Com">
<meta http-equiv="Content-Type" content="<?php echo $this->getContentType() ?>" />
<title><?php echo  Mage::app()->getWebsite()->getName(); ?> - <?php echo $this->getTitle() ?></title>
<meta name="description" content="<?php echo htmlspecialchars($this->getDescription()) ?>" />
<meta name="keywords" content="<?php echo htmlspecialchars($this->getKeywords()) ?>" />
<meta name="robots" content="<?php echo htmlspecialchars($this->getRobots()) ?>" />
<link rel="icon" href="<?php echo $this->getSkinUrl('images/icons/favicon.ico') ?>" type="image/x-icon" />
<link rel="shortcut icon" href="<?php echo $this->getSkinUrl('images/icons/favicon.ico') ?>" type="image/x-icon" />
<link rel="image_src" href="<?php echo $this->getSkinUrl(); ?>images/misc/sitethumb.png" />
<link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>skin/frontend/numanna/default/css.custom.css">
<!--[if lt IE 7]>
<script type="text/javascript">
//<![CDATA[
    var BLANK_URL = '<?php echo $this->helper('core/js')->getJsUrl('blank.html') ?>';
    var BLANK_IMG = '<?php echo $this->helper('core/js')->getJsUrl('spacer.gif') ?>';
//]]>
</script>

<![endif]-->
<?php echo $this->getCssJsHtml() ?>
<?php echo $this->getChildHtml() ?>
<?php echo $this->helper('core/js')->getTranslatorScript() ?>
<?php echo $this->getIncludes() ?>


<!-- Development Mode On Loading LESS
================================================== -->
<!--<link href="<?php echo $this->getSkinUrl('css/saddlery.less') ?>" rel="stylesheet/less" type="text/css">
<script src="<?php echo $this->getSkinUrl('js/less.js') ?>" type="text/javascript"></script>-->


<!-- HTML5 shim, for IE6-8 support of HTML5 elements
================================================== -->
<!--[if lt IE 9]>
  <script src="<?php echo $this->getSkinUrl('js/html5.js') ?>"></script>
<![endif]-->

<!-- Load PNG Fix older IE Versions
================================================== -->
<!--[if lte IE 7]>
        <script type="text/javascript" src="<?php echo $this->getSkinUrl('js/pngfix.js'); ?>"></script>
        <script type="text/javascript">DD_belatedPNG.fix('*');</script>
<![endif]-->
<!-- End Load -->

