<div class="faq clearfix">

		<div class="accordionButton">Why should I buy from NuManna with so many others out there?</div>
		<div class="accordionContent">We developed our products with our own families in mind. We wanted easy-to-fix meals that werent full of chemicals and preservatives. We also wanted a product with superior taste that our family would want to eat today or tomorrow. We have developed high-quality meals free of MSG, GMOs and other undesirable additives. We offer NuManna for a great price and give our customers several different ways to buy, including monthly shipments and package discounts. We have the highest packaging standards in the industry. 5 mm over-engineered bags with resealable tops and oxygen absorbers help provide true 25+ year shelf life. Not all storable foods are created equal. If you are considering storable foods we believe NuManna is the perfect choice for your familys pantry.</div>

		<div class="accordionButton">Where should I store my food?</div>
		<div class="accordionContent">A good rule of thumb is that your storable food is comfortable where you are. The worst enemy of storable foods is temperature fluctuation and inferior packaging that allows oxygen in. It is best to put your stores in a consistently cool, dry place. If your NuManna food is stored improperly the shelf life can be greatly diminished. A garage would be one of the worst places because of the temperature changes throughout the year. The easy stack buckets allow storage flexibility. A basement cold storage would be ideal. In your closet would work well. For maximum shelf life store at 55 degrees or cooler.</div>

		<div class="accordionButton">How much water do I need?</div>
		<div class="accordionContent">NuManna Foods uses about 1 cup of water per serving cooked. This will vary slightly among the different varieties. To help meet your water demands we offer PROPUR water filters that will allow you to have clean water in virtually any situation.</div>

		<div class="accordionButton">Why is GMO and No-Gluten so important?</div>
		<div class="accordionContent">No Gluten is not a choice for everybody. Around 1% of the population is suffering from some level of Celiac disease. Gluten intolerance can turn an ordinary loaf of bread into a health emergency. NuManna is sensitive to dietary requirements. We have listened to our customers and developed packages with 100% No Wheat ingredients.

Genetically Modified food or GMO, short for Genetically Modified Organism, is rapidly becoming one of the most controversial topics in the food world. When scientists manipulate the DNA of existing food to create new strains the overall effect on Humans is up for debate. Protein synthesis is altered. Many studies have indicated serious reasons why we should be concerned about consuming GMOs. We at NuManna have tried to eliminate such risks from our diet. If we are reluctant to eat GMOs now, why would we want to eat them in the future? Or in an emergency? Why would we want to sell them to our customers? With valid studies showing that GMOs have degenerative effects on the animals that are tested why would anyone want to risk their health on Genetically Modified ingredients if they dont have to? With NuManna you at least have a choice about GMO Free food storage.</div>

		<div class="accordionButton">How do I prepare NuManna meals?</div>
		<div class="accordionContent">Follow the directions on the package. Start by boiling the water as directed in an appropriate place. Pay attention to the amount called for. Rip open the meal of your choice, remove the oxygen absorber and pour the contents in the boiling water. Follow directions instructing you to simmer or boil or stir often. In minutes your meal will be done.</div>

		<div class="accordionButton">Are there any other uses for NuManna food?s</div>
		<div class="accordionContent">Well, pretty much anytime you would need quick, easy-to-fix meals. They are great for outdoor activities like camping, picnics, reunions, etc. We have seen our customers make NuManna a part of their everyday life. Late for baseball practice? NuManna meals are a perfect choice.

NuManna packages are specifically chosen to be flexible and mix well with other bulk stores you may already have. Have extra rice storage? Cook the rice and mix it with the chili. Now your NuManna foods can easily be extended and your bland rice becomes part of an extremely flavorful meal. This is just one example.</div>

		<div class="accordionButton">How long will NuManna food last?</div>
		<div class="accordionContent">We have put NuManna Foods in 5mm, over-engineered bags. The bags are nitrogen flushed and have an oxygen absorber to preserve freshness. The ingredients are specifically chosen for taste, quality and longevity. Through testing and manufacturing comparisons we know our storable food has a true 25+ year shelf life. If you take reasonable storage measures your NuManna food will be there when you need ittomorrow or 30 years from now.</div>

		<div class="accordionButton">What is your return policy?</div>
		<div class="accordionContent">We have a no questions asked 60 Day No Risk Money Back Guarantee.</div>

		<div class="accordionButton">Do you charge shipping?</div>
		<div class="accordionContent">We charge a small flat fee for shipping to cover the expense of the boxes and freight. Shipping is calculated at checkout.</div>

        <br class="clear"/>
        <br/><br/>


</div>


<h2>Whats Your Question?</h2>

<form action="<?php echo $this->getFormAction(); ?>" id="contactForm" method="post">
    <div class="fieldset rel">

        <ul class="form-list">

            <li class="fields">
                <div class="field">
                    <label for="name" class="required"><em>*</em><?php echo Mage::helper('contacts')->__('Name') ?></label>
                    <div class="input-box">
                        <input name="name" id="name" title="<?php echo Mage::helper('contacts')->__('Name') ?>" value="<?php echo $this->htmlEscape($this->helper('contacts')->getUserName()) ?>" class="input-text required-entry" type="text" />
                    </div>
                </div>
                <div class="field">
                    <label for="email" class="required"><em>*</em><?php echo Mage::helper('contacts')->__('Email') ?></label>
                    <div class="input-box">
                        <input name="email" id="email" title="<?php echo Mage::helper('contacts')->__('Email') ?>" value="<?php echo $this->htmlEscape($this->helper('contacts')->getUserEmail()) ?>" class="input-text required-entry validate-email" type="text" />
                    </div>
                </div>
            </li>
            <li>
                <label for="telephone"><?php echo Mage::helper('contacts')->__('Telephone') ?></label>
                <div class="input-box">
                    <input name="telephone" id="telephone" title="<?php echo Mage::helper('contacts')->__('Telephone') ?>" value="" class="input-text" type="text" />
                </div>
            </li>
            <li>
                <label for="subject"><?php echo Mage::helper('contacts')->__('Subject') ?></label>
                <div class="input-box">
              <!--       <select name="subject" id="subject" title="<?php echo Mage::helper('contacts')->__('Subject') ?>" class="input-text" >
                        <option>Option 1</option>
                        <option>Option 2</option>
                    </select> -->

                    <input name="subject" id="subject" title="<?php echo Mage::helper('contacts')->__('Subject') ?>" value="" class="input-text" type="text" />


                </div>
            </li>
            <li class="wide">
                <label for="comment" class="required"><em>*</em><?php echo Mage::helper('contacts')->__('Comment') ?></label>
                <div class="input-box">
                    <textarea name="comment" id="comment" title="<?php echo Mage::helper('contacts')->__('Comment') ?>" class="required-entry input-text" cols="5" rows="3"></textarea>
                </div>
            </li>
        </ul>
        <div class="clear"></div>
    </div>
    <div class="buttons-set">
        <input type="text" name="hideit" id="hideit" value="" style="display:none !important;" />
        <p class="required fl"><?php echo Mage::helper('contacts')->__('* Required Fields') ?></p>
        <button type="submit" title="<?php echo Mage::helper('contacts')->__('Submit') ?>" class="fr btn btn-primary"><span><span><?php echo Mage::helper('contacts')->__('Submit Question') ?></span></span></button>
    </div>
</form>
<script type="text/javascript">
//<![CDATA[
    var contactForm = new VarienForm('contactForm', true);
//]]>
</script>
