<?php
/**
 * Media Gallery & Product Videos extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   FME
 * @package    Mediaappearance
 * @copyright  Copyright 2010 © free-magentoextensions.com All right reserved
 **/
?>
<?php if(Mage::helper('mediaappearance')->getMediaEnable()):?>
<script type="text/javascript">

</script>

<?php $collection = $this->getBlockVideos(5); ?>
<?php
	$popupWidth  = Mage::getStoreConfig('mediaappearance/popupsettings/width');
	$popupHeight = Mage::getStoreConfig('mediaappearance/popupsettings/height');
	$autoPlay 	 = Mage::getStoreConfig('mediaappearance/popupsettings/autoplay');
	$playAgain 	 = Mage::getStoreConfig('mediaappearance/popupsettings/playagain');
?>
<?php if ( count($collection) == 0 ) : ?>

	<p><?php echo $this->__('No Videos yet...'); ?></p>

<?php else : ?>
           	
            <div class="block">
                <div class="block-title">
                    <strong><span><img src="<?php echo $this->getSkinUrl() ?>images/mediaappearance/tv.png" alt=" " border="none" class="tv" width="16" height="16" />&nbsp;<?php echo $this->__(Mage::helper('mediaappearance')->getVideosBlockTitle()); ?></span></strong>
                    <div class="block-content">
                    
                    	 <table width="100%" border="0" align="center" cellpadding="0" style="margin-left:0px;" cellspacing="8">
                         	 <tr>
                            	<td colspan="3">&nbsp;</td>
                            </tr>
                        	<?php $i=0; foreach ( $collection as $_media ) : ?>
                            <?php
								if($_item["mediatype"] == "1") {
						$data_type = 'data-type="swf"';
						$class= Mage::helper('mediaappearance')->is_image(Mage::getBaseUrl('media').$_item["filename"]);
						$videoURL = Mage::getBaseUrl('media').$_item["filename"];
						$videoRel = 'shadowbox;  height='.$popupHeight.';width='.$popupWidth.';options={flashVars:{skin: '.Mage::getBaseUrl('js').'mediaappearance/skin01.zip,autostart: '.autoPlay.'}}';
						 if($_item["filethumb"] != "") {
							$imgURL = Mage::helper('mediaappearance')->resizeImage($_item["filethumb"]);
						} else {
							$imgURL = Mage::getBaseUrl('media')."mediaappearance/video_icon.jpg";
						} 
						
					} elseif ($_item["mediatype"] == "2") {
						$data_type = 'data-type="iframe"';
						//For Thumb
						$videoURL = $_item["videourl"];
						$videoData = Mage::helper('mediaappearance')->video_info($_item["videourl"]);
						if ($videoData!==false) {
							if($_item["filethumb"] != "") {
									$imgURL = Mage::helper('mediaappearance')->resizeImage($_item["filethumb"]);
								} else {
									$imgURL = Mage::getBaseUrl('media')."mediaappearance/video_icon_full.jpg";
								}
							
						} else {
							if($_item["filethumb"] != "") {
								$imgURL = Mage::getBaseUrl('media').$_item["filethumb"];
							} else {
								$imgURL = Mage::getBaseUrl('media')."mediaappearance/video_icon_full.jpg";
							}
						}
						
						//For Video URL
						if ($videoData!==false) {
							
							$video_type  = $videoData['video_type'];
							$video_id    = $videoData['video_id'];
							if($video_type == "vimeo") {
								$class="fancybox";
								$videoRel = "shadowbox; height=".$popupHeight.";width=".$popupWidth.";options={flashVars:{autostart: ".$autoPlay."}}";
								$videoURL = 'http://player.vimeo.com/video/'.$video_id.'?autoplay=1';
							} elseif($video_type == "youtube") {
								$class="fancybox";
								$videoRel = 'shadowbox;  height='.$popupHeight.';width='.$popupWidth.'; options={flashVars:{autostart: '.$autoPlay.'}}';
								$videoURL = "http://www.youtube.com/embed/".$video_id;
							} 
							
						} else {
							
							$videoURL = $_item["videourl"];
							$videoRel = 'shadowbox; height='.$popupHeight.';width='.$popupWidth.';options={flashVars:{skin: '.Mage::getBaseUrl('js').'mediaappearance/skin01.zip,autostart: '.$autoPlay.'}}';
							
						}
					} else {
						$videoRel = "";
						$videoURL = "#";
						$imgURL = Mage::getBaseUrl('media')."mediaappearance/video_icon_full.jpg";
					}	
							?>
                            
                            <tr>
                                <td width="70" align="center" valign="top">
                                 <div class="mediaimage">
                                    <img src="<?php echo $imgURL; ?>" class="filmed ishadow50 ishine" width="175" height="140" alt="<?php echo $_media["title"]; ?>" border="0" />
                                    <a class="<?php echo $class?>" href="<?php echo $videoURL; ?>" title="<?php echo $_item['title']; ?>" rel="<?php echo $videoRel; ?>" data-width="<?php echo $popupWidth ?>" data-height="<?php echo $popupHeight ?>">
                                    <img src="<?php echo $this->getSkinUrl() ?>images/mediaappearance/play_icon.png" alt="" width="61" height="61" border="0" />
                                    </a>
                                </div>
                                <br />
                                <br />
                                <span class="blocktitle"><?php echo $_media["title"]; ?><br /></span>
                                </td>
                            </tr>
                            <tr>
                            	<td colspan="3">&nbsp;</td>
                            </tr>
                            <?php endforeach; ?> 
                        </table>
                    
                    </div>     
                </div>
            </div>
<?php endif; ?>
<?php endif; ?>