<?php
/**
 * Category view template
 *
 * @see Mage_Catalog_Block_Category_View
 */
?>
<?php
    $_helper    = $this->helper('catalog/output');
    $_category  = $this->getCurrentCategory();
    $_imgHtml   = '';
    if ($_imgUrl = $_category->getImageUrl()) {
        $_imgHtml = '<p class="category-image"><img src="'.$_imgUrl.'" alt="'.$this->htmlEscape($_category->getName()).'" title="'.$this->htmlEscape($_category->getName()).'" /></p>';
        $_imgHtml = $_helper->categoryAttribute($_category, $_imgHtml, 'image');
    }
?>

<?php if($_imgUrl): ?>
    <?php // echo $_imgHtml ?>

    <!-- category with image -->
    <div class="category-with-image">
        <div class="pic"><img src="<?php echo $_imgUrl ?>" alt="" /></div>
        <div class="bread"><?php  echo $this->getLayout()->getBlock("breadcrumbs")->toHtml()?></div>
        <div class="category-title">
            <?php if($this->IsRssCatalogEnable() && $this->IsTopCategory()): ?>
                <a href="<?php echo $this->getRssLink() ?>" class="link-rss"><?php echo $this->__('Subscribe to RSS Feed') ?></a>
            <?php endif; ?>
            <h1><?php echo $_helper->categoryAttribute($_category, $_category->getName(), 'name') ?></h1>
        </div>
        <?php if($_description=$this->getCurrentCategory()->getDescription()): ?>
        <div class="category-description std clearfix">
            <?php echo $_helper->categoryAttribute($_category, $_description, 'description') ?>
        </div>
        <?php endif; ?>
    </div>


    <!-- end -->

<?php else:?>

    <!-- category without image -->
    <div class="category-without-image">
      <div class="bread"><?php  echo $this->getLayout()->getBlock("breadcrumbs")->toHtml()?></div>
      <div class="category-title">
          <?php if($this->IsRssCatalogEnable() && $this->IsTopCategory()): ?>
              <a href="<?php echo $this->getRssLink() ?>" class="link-rss"><?php echo $this->__('Subscribe to RSS Feed') ?></a>
          <?php endif; ?>
          <h1><?php echo $_helper->categoryAttribute($_category, $_category->getName(), 'name') ?></h1>
      </div>
      <?php if($_description=$this->getCurrentCategory()->getDescription()): ?>
          <div class="category-description std">
              <?php echo $_helper->categoryAttribute($_category, $_description, 'description') ?>
          </div>
      <?php endif; ?>
      <!-- end -->
    </div>

<?php endif; ?>


<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>

<?php if($this->isContentMode()): ?>
    <?php echo $this->getCmsBlockHtml() ?>

<?php elseif($this->isMixedMode()): ?>
    <?php echo $this->getCmsBlockHtml() ?>
    <?php echo $this->getProductListHtml() ?>

<?php else: ?>
    <?php echo $this->getProductListHtml() ?>
<?php endif; ?>
