<div class="sample-pack">
    <div class="intro">
        <h1>Sample Pack <span>from $19.95</span></h1>
        <h2>Try It and Taste the NuManna Difference! </h2>
        <p>NuManna foods are hard to fully appreciate without tasting. They're like no other brand on the market. Words don't do them justice. That's why we decided to offer a four-recipe Sampler Pack. </p>
    </div>
    <h2>It includes:</h2>
    <img src="<?php echo $this->getSkinUrl(); ?>images/misc/pack-contents.jpg" alt="" />
    <div class="action"><div class="holder"><a href="http://numanna.transformagency.com/products/convenience-packs/propur-countertop-system-w-promax.html" class="btn btn-primary btn-large">Order Now</a></div></div>
    <p>Healthy long-term food storage solutions with great taste are exceedingly rare. Most companies in our industry give little thought to taste, or to the long-term health impact of their products' ingredients, such as Aspertame, chemical preservatives, gluten, soy, high-fructose corn syrup, GMO modifications, and other harmful additives.</p>
    <p>NuManna is the industry leader when it comes to healthy, chemically-free storable foods. And if it's got the NuManna name on it, you can be sure it's delicious. <strong> Give our Sample Pack a try and you'll appreciate the NuManna difference!</strong>  </p>

      <hr/>
      <p class="testimonial">"I received the sampler pack last week and was pleasantly surprised at how good the food is. The portion size was perfect for both my husband and I to try. His comment was, ‘this is actually really good tasting’. Also, the fact that this is non-gmo food is a major plus! We will definitely be ordering from you again. Thank you so much for a great product, and offering the sample packs to try."</p>
      <p class="author">
      <strong>— Sherrie S.</strong>
      </p>
</div>